### ISSUE TITLE
new version 0.6.8 cant find dump.dart

### ISSUE THREAD

**Issue by HuRuWo** [Impact-I/reFlutter#120]
It's nice to see that you've updated the tool version . 

I tried but didn't work very well.

I choose n 

```
I need to capture traffic only (Choose "No" if you also need a dump.dart) [Y/n]? n
```

but not work

```
adb -d shell "cat /data/data/com.example.test.flutter_demo/dump.dart" > dump.dart
cat: /data/data/com.example.test.flutter_demo/dump.dart: No such file or directory
```

**Comment by chinleez** [comment]
貌似全仓的dump的逻辑没合并进来~~

**Comment by Impact-I** [comment]
@praiseqin , @HuRuWo Sorry. 
 `pip3 install reflutter==0.7.0`

@HuRuWo still not fixed bug: lost some dart class

Thanks

**Comment by chinleez** [comment]
> 
@Impact-I 
It seems that libflutter.so downloaded in version 0.7.0/0.6.6/0.6.8 does not contain dump code, such as /data/data/xxx/dump.dart, log reflutter string. 
__init__.py
The value of patchdump variable seems to be equal to false all the time. I don't know if it's a bug

**Comment by HuRuWo** [comment]
0.7.0 also not work

**Comment by Impact-I** [comment]
@praiseqin , @HuRuWo Oh really. From version `9e2165577cef0f0f70f9ff072107920c` to `a0cb0c928b23bc17a26e062b351dc44d`
flag is not switched to `True` in v3
I make too many mistakes lately
Now I will send these versions for build

**Comment by Impact-I** [comment]
@praiseqin , @HuRuWo Build completed

Please retest:
`pip3 install reflutter==0.7.0`
`reflutter main.apk`
`2`
`java -jar uber-apk-signer.jar --allowResign -a release.RE.apk`
`adb install release.RE-aligned-debugSigned.apk`
`check /data/data/<PACKAGE_NAME>/dump.dart`
