### ISSUE TITLE
HTTP2 format error

### ISSUE THREAD

**Issue by onesecurity** [Impact-I/reFlutter#121]
HTTP2 format error.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/61774041/167603819-5f831e0f-bf22-4e1a-95a3-ed6d55612841.png">
<img width="413" alt="image" src="https://user-images.githubusercontent.com/61774041/167604013-06c9ca53-0579-4d71-be7e-a8d4cf5ac0bc.png">

**Comment by Impact-I** [comment]
Hi @onesecurity , Thanks for your interest in the project!

Try disabling http/2 in BurpSuite:

Project Options -> HTTP -> HTTP/2 Uncheck
Proxy Tab -> Options -> Proxy Listeners -> Edit -> HTTP Tab -> Support HTTP/2 Uncheck

**Comment by onesecurity** [comment]
The App has HTTP2 enabled by default and cannot degrade so this causes the issue.

**Comment by onesecurity** [comment]
Downgrade the request in the App to HTTP1.1 to solve the problem.
