### ISSUE TITLE
Don't get dump.dart

### ISSUE THREAD

**Issue by cryptax** [Impact-I/reFlutter#130]
I've run reflutter on my Android apk, aligned and signed the apk. Setup Burp Suite.
Now, I install the signed apk on Android and run it. **Basically, nothing happens.** But _I'm not sure I'm using reflutter correctly._

- Am I meant to see anything special in **Burp Suite**? I don't. I did configure proxy 8083 and invisible mode. Anything else?
- Am I meant to configure something on the **Android** smartphone?
- My smartphone is connected to the same **wifi** as the laptop running the Burp Suite. The smartphone can ping the laptop. When I ran `reflutter`, I provided the IP address of the laptop.

On the smartphone, I have **no** `dump.dart` in `/data/data/<PACKAGE_NAME>`.
I have no `DartVM` in logcat. I do have a few `Dart`  - I believe those are IP addresses the app contacts.

```
$ adb logcat | grep -i Dart
05-10 13:14:04.471 16371 16403 E Dart    : ref: 148.251.68.92
05-10 13:14:04.681 16371 16403 E Dart    : ref: 216.58.209.227
05-10 13:14:04.682 16371 16403 E Dart    : ref: 216.58.209.227
05-10 13:19:30.818 16371 16403 E Dart    : ref: 148.251.68.92
05-10 13:20:31.004 16371 16403 E Dart    : ref: 148.251.68.92
```

I have nothing relevant for `reflutter` tag (same with `adb logcat | grep -i reflutter`):

```
$ adb logcat -e reflutter
--------- beginning of crash
--------- beginning of main
05-10 13:19:05.804  8249  8249 E adbd    : service_to_fd: shell,v2,TERM=xterm-256color:export ANDROID_LOG_TAGS="''"; exec logcat '-e' 'reflutter'
--------- beginning of system
05-10 13:36:06.996  8249  8249 E adbd    : service_to_fd: shell,v2,TERM=xterm-256color:export ANDROID_LOG_TAGS="''"; exec logcat '-e' 'reflutter'
```

More info: 

- My app is using Flutter **2.13** (`e4a09dbf2bb120fe4674e0576617a0dc`)
- I've installed Reflutter from sources (**0.7.0**)
- I'm on Linux

**Comment by Impact-I** [comment]
Hi @cryptax 

Thank you for your interest in the project!

Could you pass:
`pip3 install reflutter==0.7.0`
`reflutter main.apk`
`2`
`java -jar uber-apk-signer.jar --allowResign -a release.RE.apk`
`adb install release.RE-aligned-debugSigned.apk`
`adb logcat -e reFlutter`
`check /data/data/<PACKAGE_NAME>/dump.dart`

The engine for you was wrong.
It was fixed 10 minutes ago.

**Comment by Impact-I** [comment]
@cryptax Successfully?

**Comment by cryptax** [comment]
@Impact-I Thanks for your fast response!! Yes! It works far better. Now I have `dump.dart` :+1: 

Is the code in `dump.dart` normal though?

```
Library:'dart:core' Class: Object {
  J _kh@0150898 = sentinel ;
 
  Function '_mh@0150898': static. (dynamic) => String { 

               Code Offset: _kDartIsolateSnapshotInstructions + 0x0000000000239834
       
       }
 
  Function '_haveSameRuntimeType@0150898': static. (dynamic, dynamic) => bool { 

               Code Offset: _kDartIsolateSnapshotInstructions + 0x000000000007e344
       
       }
 ```      

You see? It's just code offsets.

**Comment by Impact-I** [comment]
@cryptax Thanks for testing.
No. Selecting 1 disables dump.

It is not known if the offsets are correct here.
Despite the fact that I test a large number of engines with different applications, the offsets may not be correct. There are many engines and bugs can be.
You can find a function you are sure of and check if the offsets are correct using the frida script or ghidra

**Comment by cryptax** [comment]
@Impact-I am I not expected to find the "decompiled" source code in `dump.dart`? There's another step?

**Comment by Impact-I** [comment]
@cryptax Unfortunately no. But you can go to functions in Ghidra and use frida if the offset is correct.
Also, keep in mind that the code can be obfuscated, which will complicate your analysis at times.
