### ISSUE TITLE
Possibility to Support Flutter v1 apps?

### ISSUE THREAD

**Issue by gowthaman-basuvaraj** [Impact-I/reFlutter#165]
i have an app that is built with Flutter v1, anyway to support that version?

**Comment by Impact-I** [comment]
@gowthaman-basuvaraj v1 = v2

Choose an option:

 (v1 = v2) = 1. Traffic monitoring and interception

**Comment by gowthaman-basuvaraj** [comment]
OKay, got it but the script is printing

wait...
af51afceb8886cc11e25047523c4e0c7e1f5d408

and stops.

i debugged and it seems to try to download from the Url

https://github.com/Impact-I/reFlutter/releases/download/android-v2-20e5c4f7dc44368ac5a17643b93665f6/libflutter_arm64.so

which does not exist

**Comment by Impact-I** [comment]
@gowthaman-basuvaraj You have a rather old version of the engine. In the current repository, support only starts from version [v1.15.17](https://github.com/Impact-I/reFlutter/blob/main/enginehash.csv)
I'll try now, make an engine for you
If you have an engine from the old repository for version `20e5c4f7dc44368ac5a17643b93665f6` take it and place it in the archive manually

**Comment by Impact-I** [comment]
@gowthaman-basuvaraj Build completed
Please try again

Thanks

**Comment by gowthaman-basuvaraj** [comment]
Awesome, Works Brilliantly , Thanks a lot

**Comment by qolbudr** [comment]
mine keep stoped on this @Impact-I 

wait....
b863200c37df4ed378042de11c4e9ff34e4e58c9
