### ISSUE TITLE
App can not be run on Android

### ISSUE THREAD

**Issue by iperfectapp** [Impact-I/reFlutter#180]
I followed the instructions from README and use uber-apk-signer to make the apk aligned and signed.

The apk was installed successfully. However, when I tried to open it, it crashed immediately.

The original apk file can be downloaded at [here](https://newplayer.oss-cn-hangzhou.aliyuncs.com/main.apk), and my refluttered version is 0.7.1

Thanks verymuch!!!

**Comment by Impact-I** [comment]
Hi @iperfectapp 
Thanks for your interest in the project!

1. downloaded at [here](https://newplayer.oss-cn-hangzhou.aliyuncs.com/main.apk)
2. `java -jar uber-apk-signer.jar --allowResign -a main.apk`
3. `install main-aligned-debugSigned.apk`
4. crash app **without** use reFlutter

It's not a reFlutter problem
Probably the application has integrity/signature checks

**Comment by iperfectapp** [comment]
Thanks very much!

**Comment by iperfectapp** [comment]
@Impact-I And Is there a way  to download ipa from App Store?
