### ISSUE TITLE
No  Hook Function output

### ISSUE THREAD

**Issue by iperfectapp** [Impact-I/reFlutter#183]
I wrote a demo,but no output print
<img width="1192" alt="截屏2022-05-17 下午12 53 04" src="https://user-images.githubusercontent.com/3021764/168731925-ffbdb39d-eac8-44c7-879e-f91a64064ffe.png">

**Comment by Impact-I** [comment]
Hello @iperfectapp 
Thanks for your interest in the project!

What is your Snapshot Hash ?
