### ISSUE TITLE
run the new ipa file is crash

### ISSUE THREAD

**Issue by pythonName** [Impact-I/reFlutter#185]
the crash info:

Termination Description: DYLD, Symbol not found: _FlutterMethodNotImplemented | Referenced from: /private/var/containers/Bundle/Application/368803BE-CAAC-4220-BA25-4534752D6570/Runner.app/Frameworks/audioplayers.framework/audioplayers | Expected in: /private/var/containers/Bundle/Application/368803BE-CAAC-4220-BA25-4534752D6570/Runner.app/Frameworks/Flutter.framework/Flutter | in /private/var/containers/Bundle/Application/368803BE-CAAC-4220-BA25-4534752D6570/Runner.app/Frameworks/audioplayers.framework/audioplayers

**Comment by Impact-I** [comment]
Hello @pythonName 
Thanks for your interest in the project!

What is your snapshot hash?

**Comment by pythonName** [comment]
SnapshotHash: d56742caf7b3b3f4bd2df93a9bbb5503

**Comment by Impact-I** [comment]
@pythonName try replacing the engine manually https://github.com/Impact-I/reFlutter/releases/tag/ios-v2-d56742caf7b3b3f4bd2df93a9bbb5503

**Comment by pythonName** [comment]
> @pythonName try replacing the engine manually https://github.com/Impact-I/reFlutter/releases/tag/ios-v2-d56742caf7b3b3f4bd2df93a9bbb5503

thanks, it's works fine.

and this is the dump.dart content:
<img width="859" alt="图片" src="https://user-images.githubusercontent.com/4724735/170814675-80efee98-466b-4f25-8568-e61366120515.png">

Does this mean that dart code is confused？
