### ISSUE TITLE
how to get   HASH_PATCH=[Snapshot_Hash]        -e COMMIT=[Engine_commit] 

### ISSUE THREAD

**Issue by ghost** [Impact-I/reFlutter#187]
how to get   HASH_PATCH=[Snapshot_Hash]   
    -e COMMIT=[Engine_commit]       in lib flutter.so or lib app.so ?

**Comment by ghost** [comment]
I don't know how to get Snapshot_Hash  and Engine_commit in my app

**Comment by ghost** [comment]
I don't know how to get params  Engine_commit in my apk？

**Comment by ghost** [comment]
I was figure out for  Snapshot_Hash，but I don't know how to get Engine_commit ？

**Comment by Impact-I** [comment]
@xhtechxposed You can get it from this spreadsheet https://github.com/Impact-I/reFlutter/blob/main/enginehash.csv
if it's not in the table you need to find it here https://github.com/flutter/engine/blob/486f4a749e532b865d5d24990d865f7d902b8fb3/DEPS

486f4a749e532b865d5d24990d865f7d902b8fb3 - Engine_commit
