### ISSUE TITLE
1441d6b13b8623fa7fbf61433abebd31 unable to get dump 

### ISSUE THREAD

**Issue by hxhooker** [Impact-I/reFlutter#188]
this hash unable to get dump

**Comment by hxhooker** [comment]
I used the latest version

**Comment by Impact-I** [comment]
Hi @hxhooker ,
Thanks for your interest in the project!
Is your app crashing? Are you using Android or IOS? Is traffic intercepted?

**Comment by hxhooker** [comment]
@Impact-I  hello ,.thx for your reply .  no crashing .. it is android app ..and I just use  2. Display absolute code offset for functions .  but in the data/data/packeagename  folder I can't found the dump.dart..  if you want .here you can get the apk:
https://play.google.com/store/apps/details?id=com.okinc.okex.gp&hl=zh&gl=US

**Comment by Impact-I** [comment]
@hxhooker I will try to reproduce it during the day.
What version of Android do you have?

**Comment by hxhooker** [comment]
I tested in 8.1 and 12.0  ,both of them didnt worked

**Comment by hxhooker** [comment]
I don't know why , I tested other apks .   all worked

**Comment by hxhooker** [comment]
@Impact-I  any idea?

**Comment by Impact-I** [comment]
@hxhooker The main logic of the application is written in kotlin, what functionality in the flutter are you interested in?

**Comment by hxhooker** [comment]
the encrypt functionality

**Comment by Impact-I** [comment]
@hxhooker Are you sure that it is implemented on the flutter side?

**Comment by Impact-I** [comment]
@hxhooker I tested 1441d6b13b8623fa7fbf61433abebd31-engine. The dump succeeds.

The app you listed uses flutter in rare situations. If you don't find the dump.dart file, it probably means that the flutter library was never used.

**Comment by hxhooker** [comment]
@Impact-I  have you got the dump.dart with  1441d6b13b8623fa7fbf61433abebd31-engine?

**Comment by hxhooker** [comment]
if just pip install refuter ? or need to replace the lib flutter.so ?

**Comment by Impact-I** [comment]
> @Impact-I have you got the dump.dart with 1441d6b13b8623fa7fbf61433abebd31-engine?

Yes

**Comment by Impact-I** [comment]
> if just pip install refuter ? or need to replace the lib flutter.so ?

It does not matter.

**Comment by hxhooker** [comment]
hmm :)  which version android you used ?

**Comment by Impact-I** [comment]
> hmm :) which version android you used ?

Android 10. But I got dump.dart for my test app. Not what you provided.

**Comment by hxhooker** [comment]
I am sure.the app used the flutter ,but don't know why can't get the dump.dart

**Comment by hxhooker** [comment]
because the app. have the libapp.so and libflutter.so and it used flutter to send some https request

**Comment by hxhooker** [comment]
you can get the apk from here :
https://apkcombo.com/zh/okx-buy-bitcoin-eth-crypto/com.okinc.okex.gp/download/apk

**Comment by hxhooker** [comment]
the newest version used flutter :)

**Comment by hxhooker** [comment]
worked now .thx bro

**Comment by Impact-I** [comment]
@hxhooker I'm glad it worked. Tell us in what functionality flutter is used. Is the code in dump.dart obfuscated?

**Comment by hxhooker** [comment]
not obfuscated  .it used the aes and hmac

**Comment by hxhooker** [comment]
thx for your help  👍
