### ISSUE TITLE
reFlutter is not working with Debug APK

### ISSUE THREAD

**Issue by vinilnarayan** [Impact-I/reFlutter#189]
Hi,

First of all, this is a good project. I really like this.
I reFluttered many iOS and android application with this. But now I'm facing an issue with reFluttering Debug APK (release APK is not working with Genymotion, So that only I'm working with Debug APK). It showing a message like below.

<img width="570" alt="Screenshot 2022-06-02 at 9 13 40 AM" src="https://user-images.githubusercontent.com/46709848/171549182-19b54dcf-0c03-4fbf-833d-7a83b78dee7a.png">

Could you please help me to do the same process with Debug APK as well.

Thanks,
Vinil

**Comment by Impact-I** [comment]
Hi @vinilnarayan 
Thanks for your interest in the project!
Debug APKs are not supported.

**Comment by vinilnarayan** [comment]
Hi @Impact-I ,

Can you consider this as a request and implement ?

**Comment by Impact-I** [comment]
@vinilnarayan No. Explore the Flutter device. To understand why your request will not be considered. Thank you!
