### ISSUE TITLE
no dump.dart generated

### ISSUE THREAD

**Issue by DiamondHunters** [Impact-I/reFlutter#193]
I have repacked apk and run it on phone,but no dump.dart at `/data/data/<PACKAGE_NAME>/`

SnapshotHash: 1441d6b13b8623fa7fbf61433abebd31

**Comment by xiaokanghub** [comment]
me too.
``` 
SnapshotHash: d56742caf7b3b3f4bd2df93a9bbb5503
```

**Comment by Impact-I** [comment]
@DiamondHunters @xiaokanghub I checked in these engines dump file is written. Attach apk
Thanks!

**Comment by xiaokanghub** [comment]
> @DiamondHunters @xiaokanghub I checked in these engines dump file is written. Attach apk Thanks!

https://drive.google.com/file/d/1P5XWXXEW6elOt9PpkgQvSUxVtny2NH4Y/view?usp=sharing.
I tested it on reflutter-0.7.2

**Comment by DiamondHunters** [comment]
[BlueBird.apk.zip](https://github.com/Impact-I/reFlutter/files/8999392/BlueBird.apk.zip)
Here it is.Maybe it's caused by something on my phone?I have tried another apk and it run well but no dump to.

**Comment by xiaokanghub** [comment]
> [BlueBird.apk.zip](https://github.com/Impact-I/reFlutter/files/8999392/BlueBird.apk.zip) Here it is.Maybe it's caused by something on my phone?I have tried another apk and it run well but no dump to.

3/5000 
unfortunately, I can't run the BlueBird on my phone :)
```
Choose an option:

 1. Traffic monitoring and interception
 2. Display absolute code offset for functions

 [1/2]? 2

 This mode is only for dump and offset output, slow application operation is possible (network patch is still left)

Example: (192.168.1.154) etc.
Please enter your BurpSuite IP: 192.167.2.29
 Wait...


SnapshotHash: 1441d6b13b8623fa7fbf61433abebd31
The resulting apk file: ./release.RE.apk
Please sign,align the apk file

Configure Burp Suite proxy server to listen on *:8083
Proxy Tab -> Options -> Proxy Listeners -> Edit -> Binding Tab

Then enable invisible proxying in Request Handling Tab
Support Invisible Proxying -> true

source:
        C:\Users\xkang\Desktop
zipalign location: BUILT_IN
        C:\Users\xkang\AppData\Local\Temp\uapksigner-5502719484506456370\win-zipalign_29_0_2.exe5031577299382738960.tmp
keystore:
        [0] f38fb02d C:\Users\xkang\.android\debug.keystore (DEBUG_ANDROID_FOLDER)

01. release.RE.apk

        SIGN
        file: C:\Users\xkang\Desktop\release.RE.apk (21.52 MiB)
        checksum: 28a181c41c8b528cf27565d71ccc3e3d743bbc4d445fcf712c52a6f58f046fd4 (sha256)
        - zipalign success
        - sign success

        VERIFY
        file: C:\Users\xkang\Desktop\release.RE-aligned-debugSigned.apk (21.52 MiB)
        checksum: d4449642ac61cbad220f696755b8cd9f12a7e7e6637abcf2844d07278d5e8265 (sha256)
        - zipalign verified
        - signature verified [v1, v2, v3]
                45 warnings
                Subject: C=US, O=Android, CN=Android Debug
                SHA256: 12f71c4e57fd5874c3b678d3da11025f2090a72a380c117cd4c0012683c5ad56 / SHA1withRSA
                Expires: Tue Apr 19 16:30:04 CST 2050

[Tue Jun 28 17:18:35 CST 2022][v1.2.1]
Successfully processed 1 APKs and 0 errors in 3.41 seconds.
```
it looks fine

**Comment by xiaokanghub** [comment]
> [BlueBird.apk.zip](https://github.com/Impact-I/reFlutter/files/8999392/BlueBird.apk.zip) Here it is.Maybe it's caused by something on my phone?I have tried another apk and it run well but no dump to.

my env:
pixel 4 and android 10

**Comment by xiaokanghub** [comment]
@Impact-I  any idea? here is some runtime info.
```
xkang@WIN  ~\Desktop  reflutter .\Hyppe.apk

 Choose an option:

 1. Traffic monitoring and interception
 2. Display absolute code offset for functions

 [1/2]? 2

 This mode is only for dump and offset output, slow application operation is possible (network patch is still left)

Example: (192.168.1.154) etc.
Please enter your BurpSuite IP: 192.167.2.29
 Wait...

SnapshotHash: d56742caf7b3b3f4bd2df93a9bbb5503
The resulting apk file: ./release.RE.apk
Please sign,align the apk file

Configure Burp Suite proxy server to listen on *:8083
Proxy Tab -> Options -> Proxy Listeners -> Edit -> Binding Tab

Then enable invisible proxying in Request Handling Tab
Support Invisible Proxying -> true

 xkang@WIN  ~\Desktop  java -jar uber-apk-signer.jar --allowResign -a release.RE.apk
source:
        C:\Users\xkang\Desktop
zipalign location: BUILT_IN
        C:\Users\xkang\AppData\Local\Temp\uapksigner-6110886046023957306\win-zipalign_29_0_2.exe6585722873550189045.tmp
keystore:
        [0] f38fb02d C:\Users\xkang\.android\debug.keystore (DEBUG_ANDROID_FOLDER)

01. release.RE.apk

        SIGN
        file: C:\Users\xkang\Desktop\release.RE.apk (66.38 MiB)
        checksum: 19267bb6e75a171647a52764cab2d155ead88632af425005ac462249d68ad774 (sha256)
        - zipalign success
        - sign success

        VERIFY
        file: C:\Users\xkang\Desktop\release.RE-aligned-debugSigned.apk (66.4 MiB)
        checksum: a1082149b1df17b9721b0183d73cfdf30c077a69f4a137a40d172d41851392b3 (sha256)
        - zipalign verified
        - signature verified [v1, v2, v3]
                77 warnings
                Subject: C=US, O=Android, CN=Android Debug
                SHA256: 12f71c4e57fd5874c3b678d3da11025f2090a72a380c117cd4c0012683c5ad56 / SHA1withRSA
                Expires: Tue Apr 19 16:30:04 CST 2050

[Fri Jul 01 09:46:33 CST 2022][v1.2.1]
Successfully processed 1 APKs and 0 errors in 7.44 seconds.
 xkang@WIN  ~\Desktop  adb install .\release.RE-aligned-debugSigned.apk
Performing Streamed Install
Success
 xkang@WIN  ~\Desktop  adb logcat -e reFlutter
--------- beginning of crash
--------- beginning of system
--------- beginning of main
07-01 09:47:10.551 22610 22696 E DartVM  : reFlutter
07-01 09:47:10.775 22610 22811 E DartVM  : reFlutter
```

**Comment by vividmuse** [comment]
No problem I got it
[hyppe.dart.zip](https://github.com/Impact-I/reFlutter/files/9026563/hyppe.dart.zip)


> [BlueBird.apk.zip](https://github.com/Impact-I/reFlutter/files/8999392/BlueBird.apk.zip) Here it is.Maybe it's caused by something on my phone?I have tried another apk and it run well but no dump to.

**Comment by xiaokanghub** [comment]
> No problem I got it [hyppe.dart.zip](https://github.com/Impact-I/reFlutter/files/9026563/hyppe.dart.zip)
> 
> > [BlueBird.apk.zip](https://github.com/Impact-I/reFlutter/files/8999392/BlueBird.apk.zip) Here it is.Maybe it's caused by something on my phone?I have tried another apk and it run well but no dump to.

hmmm :), I tested it on Android 10 Pixel4, run well, but don't have this dump file

**Comment by DiamondHunters** [comment]
> No problem I got it [hyppe.dart.zip](https://github.com/Impact-I/reFlutter/files/9026563/hyppe.dart.zip)
> 
> > [BlueBird.apk.zip](https://github.com/Impact-I/reFlutter/files/8999392/BlueBird.apk.zip) Here it is.Maybe it's caused by something on my phone?I have tried another apk and it run well but no dump to.

thks.I will check what going on to my phone

**Comment by vividmuse** [comment]
> 

你看是不是没有存储权限?

**Comment by xiaokanghub** [comment]
> > 
> 
> 你看是不是没有存储权限?

我 dump dex 写到这个目录都可以的

**Comment by Real-Simplicity** [comment]
我和你问题一样，我的版本号也是和你一样的，你是怎么解决的？
I have the same problem as you. My SnapshotHash number is the same as yours. How do you solve it?

**Comment by DiamondHunters** [comment]
暂时没有去解决，可以试试换个设备

从 Windows 版邮件发送

发件人: 返璞归真
发送时间: 2022年8月15日 0:37
收件人: Impact-I/reFlutter
抄送: DiamondHunters; Mention
主题: Re: [Impact-I/reFlutter] no dump.dart generated (Issue #193)

我和你问题一样，我的版本号也是和你一样的，你是怎么解决的？
I have the same problem as you. My SnapshotHash number is the same as yours. How do you solve it?

**Comment by DiamondHunters** [comment]
> 我和你问题一样，我的版本号也是和你一样的，你是怎么解决的？ I have the same problem as you. My SnapshotHash number is the same as yours. How do you solve it?

暂时没有去解决，可以试试换个设备
