### ISSUE TITLE
 This engine is currently not supported.

### ISSUE THREAD

**Issue by EthicalHCOP** [Impact-I/reFlutter#201]
Hello, i'm using the lasted version on linux and windows. But y got the bellow error when y try to intercept the traffic for an apk.

IN:
`reflutter app-release.apk

 Choose an option:

 1. Traffic monitoring and interception
 2. Display absolute code offset for functions

 [1/2]? 1

 Engine SnapshotHash: 1cd6f11bc2398d18197e1822f4b5437b

 This engine is currently not supported.
 Most likely this flutter application uses the Debug version engine which you need to build manually using Docker at the moment.
 More details: https://github.com/Impact-I/reFlutter`

**Comment by PENNYWISE-45** [comment]
Same problem here too bro I'm using latest version too

**Comment by PENNYWISE-45** [comment]
This mode is only for dump and offset output, slow application operation is possible (network patch is still left)                                                                                                   Engine SnapshotHash: 07102f97a833cd8e2879e349dc16d271
                                                                        This engine is currently not supported.                                Most likely this flutter application uses the Debug version engine which you need to build manually using Docker at the moment.               More details: https://github.com/Impact-I/reFlutter

**Comment by junges521** [comment]
https://github.com/Impact-I/reFlutter/issues/201
 Engine SnapshotHash: b6d0a1f034d158b0d37b51d559379697

 This engine is currently not supported.
 Most likely this flutter application uses the Debug version engine which you need to build manually using Docker at the moment.
 More details: https://github.com/Impact-I/reFlutter

**Comment by EnhboldH** [comment]
Did you solve this problem? I'm facing the same error.

**Comment by zenahmad10** [comment]
I'm Problem too....any update solved this issue??

**Comment by jayluxferro** [comment]
> #201 Engine SnapshotHash: b6d0a1f034d158b0d37b51d559379697
> 
> This engine is currently not supported. Most likely this flutter application uses the Debug version engine which you need to build manually using Docker at the moment. More details: https://github.com/Impact-I/reFlutter

Try this, I build the engine for snapshot: b6d0a1f034d158b0d37b51d559379697
`pip3 install git+https://github.com/jayluxferro/reFlutter`

**Comment by suhaib-raadan** [comment]
I'm facing the same error.
Did you solve this problem?
no one of the solutions above worked

**Comment by zenahmad10** [comment]
> I'm facing the same error. Did you solve this problem? no one of the solutions above worked

My friend tried to install burpsuite cert into the system (root) and not on the user..the result was successful when running reflutter.

**Comment by wrteam-sagar** [comment]
does anyone has any solution or the explanation of this issue ?

**Comment by Anon-surf-max** [comment]
i have an solution for this.....which apk throw an error while reflutterring just search that app in apk combo and download the same apk and just decoumpile that apk after that just copy the lib folder and replace that lib folder with your error apk and after that just reflutter...its tested and 100% work

**Comment by jayluxferro** [comment]
> #201 Engine SnapshotHash: b6d0a1f034d158b0d37b51d559379697
> 
> This engine is currently not supported. Most likely this flutter application uses the Debug version engine which you need to build manually using Docker at the moment. More details: https://github.com/Impact-I/reFlutter

@junges521 , the engines have been built now so you can use the current version of reFlutter and that should work.

**Comment by wrteam-sagar** [comment]
> > #201 Engine SnapshotHash: b6d0a1f034d158b0d37b51d559379697
> > This engine is currently not supported. Most likely this flutter application uses the Debug version engine which you need to build manually using Docker at the moment. More details: https://github.com/Impact-I/reFlutter
> 
> @junges521 , the engines have been built now so you can use the current version of reFlutter and that should work.

@jayluxferro Wow. This package worked for me. But I have one question. Why does it worked with your tool and not with the original tool ? Are you building custom patches by your own in your forked repo ? If yes, then can you please share the exact method for building custom patches as in the original documentation it is quite confusing. And if possible I will also contribute in you package. Thank you

**Comment by jayluxferro** [comment]
@wrteam-sagar , the engines have been built now. Kindly revert to the original tool and it should work fine now.

**Comment by Impact-I** [comment]
@jayluxferro Thank you! I need to add you to PyPI. Could you put your username here (pypi.org).

**Comment by jayluxferro** [comment]
> @jayluxferro Thank you! I need to add you to PyPI. Could you put your username here (pypi.org) or email it to: [routeros7.1@gmail.com](mailto:routeros7.1@gmail.com)

@Impact-I , username: `jayluxferro`
