### ISSUE TITLE
Snapshot not compatible with the current VM configuration

### ISSUE THREAD

**Issue by hfy666** [Impact-I/reFlutter#203]
i use `reflutter xxx.ipa` generate  release.RE.ipa

reflutter==0.7.2

```
SnapshotHash: 1441d6b13b8623fa7fbf61433abebd31
The resulting ipa file: ./release.RE.ipa
Please install the ipa file
```

after install release.RE.ipa and start app
occur some issue

`[VERBOSE-3:dart_vm_initializer.cc(22)] Error while initializing the Dart VM: Snapshot not compatible with the current VM configuration: the snapshot requires 'product no-code_comments no-dwarf_stack_traces_mode lazy_async_stacks no-lazy_dispatchers dedup_instructions no-asserts arm64-sysv no-compressed-pointers null-safety' but the VM has 'product no-code_comments no-dwarf_stack_traces_mode lazy_async_stacks no-lazy_dispatchers dedup_instructions no-asserts arm64-sysv compressed-pointers null-safety'`

how do i fix it?

**Comment by hpmmrajbs** [comment]
Hi, We are also facing the same issue 

reflutter==0.7.2

SnapshotHash: 1441d6b13b8623fa7fbf61433abebd31
The resulting ipa file: ./release.RE.ipa
Please install the ipa file

**Comment by dgrivera** [comment]
same here, after patching the app via reflutter 0.7.2, then start the application it crashes.

please for your usual support,  good sir.

**Comment by dgrivera** [comment]
Any update good sir? @Impact-I

**Comment by 1091026029** [comment]
any update,sir?
