### ISSUE TITLE
Unable to install IPA with reFlutter - does not contain an application bundle

### ISSUE THREAD

**Issue by hpmmrajbs** [Impact-I/reFlutter#209]
Once re fluttered, the IPA file cannot be installed and failed with the error message as "... does not contain an application bundle, so it cannot be installed on ..."

I used XReSign to https://github.com/xndrs/XReSign to resign the IPA. It's installed but crashed on start.
SnapshotHash: 1441d6b13b8623fa7fbf61433abebd31

**Comment by jayluxferro** [comment]
@hpmmrajbs , you can use http://dantheman827.github.io/ios-app-signer/
