### ISSUE TITLE
did not match flutter engine version

### ISSUE THREAD

**Issue by HuChundong** [Impact-I/reFlutter#210]
ios ipa file, the Flutter is in 
My\ BMW.app/Frameworks/Flutter.framework/Flutter
and the version in My\ BMW.app/Frameworks/Flutter.framework/Info.plist
it's 57d3bac3dd5cb5b0e464ab70e7bc8a0d8cf083ab

but reflutter said:

 Engine SnapshotHash: d7d7d7d7d7d7d7d7d7d7d7d7d7d7d7d7
 This engine is currently not supported.

**Comment by kevinmou** [comment]
excuse me,Have you solved the problem? I met the same question.
in Frameworks/Flutter.framework/Info.plist,the FlutterEngine is 857bd6b74c5eb56151bfafe91e7fa6a82b6fee25.

![11](https://user-images.githubusercontent.com/3231578/227694153-a9cc8c46-de7b-41d9-90cc-5daf24444577.jpg)
