### ISSUE TITLE
Getting Error ' This engine is currently not supported' in Reflutter

### ISSUE THREAD

**Issue by keyurvala** [Impact-I/reFlutter#219]
Hello Brother,

Thanks for creating such an awesome tool but I am trying to generate the reflutter APK with one of my flutter applications. Unfortunately, the application showing the below error can you help me to resolve this issue,

` This engine is currently not supported.
 Most likely this flutter application uses the Debug version engine which you need to build manually using Docker at the moment.
 More details: https://github.com/Impact-I/reFlutter`

[Click Here to View Image](https://i.ibb.co/hDKz8Gy/screen-05.png)

Thanks,
Keyur

**Comment by Alphaarun3** [comment]
I too faced the same, @Impact-I can you please provide us docker usage documentation

**Comment by PwS** [comment]
Duplicate [#201 ]

**Comment by suhaib-raadan** [comment]
Duplicate  [201](https://github.com/Impact-I/reFlutter/issues/201)

**Comment by kevinmou** [comment]
![11](https://user-images.githubusercontent.com/3231578/227692135-84acc0a6-5eaa-464b-b3c5-151ab820b9e6.jpg)
i reverse an iOS ipa,also like this. how to recompiled a reflutter tool for iOS.
