### ISSUE TITLE
How to customize and compile flutter.

### ISSUE THREAD

**Issue by deadash** [Impact-I/reFlutter#222]
I see that the readme mentions a dockerfile, but I don't find where the code is.

The dump.dart run out using reflutter is missing a lot of addresses

**Comment by wrteam-sagar** [comment]
have you able to find the exact way on how to do custom patch using docker file ?

**Comment by jayluxferro** [comment]
@deadash & @wrteam-sagar , Dockerfile has been added here: https://github.com/Impact-I/reFlutter#custom-build
