### ISSUE TITLE
I reflutter an iOS ipa,"this engine is currently not supported".

### ISSUE THREAD

**Issue by kevinmou** [Impact-I/reFlutter#224]
![11](https://user-images.githubusercontent.com/3231578/227695847-097de341-cb09-421e-85fc-b099503b775a.jpg)
Hello ,I reflutter an iOS ipa,messaged like this,how to recompile this reflutter tool? the script below : https://github.com/Impact-I/ForkForFlutter/blob/main/searchSnapshot.sh. is only for Android?

**Comment by jayluxferro** [comment]
@kevinmou, this shows a modified snapshot hash. You can use a manual approach to detect the engine hash, download it and replace it in the application.
