### ISSUE TITLE
Hanging for hours when trying to build using docker

### ISSUE THREAD

**Issue by mSharif10** [Impact-I/reFlutter#225]
I tried to use the docker image. and it hanged there:

```
[1:25:29] Still working on:

[1:25:29]   src/third_party/flatbuffers

[1:25:29]   src/third_party/imgui

[1:25:29]   src/third_party/json

[1:25:29]   src/third_party/pkg/googleapis

[1:25:29]   src/third_party/swiftshader
```

before reaching the above log I run: 

`sudo docker run -e WAIT=1000 -e x64=0 -e arm=0 -e HASH_PATCH=adb4292f3ec25074ca70abcd2d5c7251 -e COMMIT=ada363ee93b17cfe31587b5102679885cb40837e --rm -iv${PWD}:/t ptswarm/reflutter`

with docker windows desktop with WSL integration. but failing this. please help with this.

**Comment by jayluxferro** [comment]
@mSharif10 , Dockerfile has been added here: https://github.com/Impact-I/reFlutter#custom-build
