### ISSUE TITLE
can I filter 127.0.0.1?

### ISSUE THREAD

**Issue by xizyy** [Impact-I/reFlutter#227]
I want to filter 127.0.0.1, so I read the source of __init__.py, maybe I need to modify socket.cc? But I don't know how to change it.(ㄒoㄒ)

**Comment by jayluxferro** [comment]
@xizyy , can you explain what exactly you want to do?

**Comment by xizyy** [comment]
@jayluxferro ，I want to grab an APP's traffic, but most of the APP's traffic is sent to a port of 127.0.0.1 first. I guess it's the websocket. However, the socket.cc patch sent traffic to 127.0.0.1 to Burpsuite, causing the application to go offline.so I can't grab the traffic.

**Comment by xizyy** [comment]
@jayluxferro ，I would like to modify the patch of socket.cc if possible. I read the documentation and source code and guessed that I might need to pull docker, but I tried to run the images many times and failed.

**Comment by jayluxferro** [comment]
@xizyy , let me try and get the docker working then you can try and see if it will solve your issue. Hopefully this weekend.

**Comment by xizyy** [comment]
@jayluxferro ，wowww,thanks,really

**Comment by jayluxferro** [comment]
@xizyy , Dockerfile has been added here: https://github.com/Impact-I/reFlutter#custom-build
