### ISSUE TITLE
network issues after reflutter

### ISSUE THREAD

**Issue by gowthaman-basuvaraj** [Impact-I/reFlutter#237]
app available from https://docs.ewaybillgst.gov.in/NicShield/NIC-Shield-Android.html

without reflutter, the app works, properly, after reflutter i can see that requests are being sent, but no response is received in burp suite

<img width="500" alt="image" src="https://github.com/Impact-I/reFlutter/assets/117379/1e96d2b8-862e-4cdf-9d60-f5bd473dadac">

any idea what could be happening ?

the curl works as intended, i.e when right click, copy as curl command and run in terminal, so i am guessing its something to do with dart/flutter?

**Comment by jayluxferro** [comment]
@gowthaman-basuvaraj , I checked and this has nothing to do with reFlutter. I'm able to get both request and response captured in Burp.

![Screenshot 2023-06-11 at 5 53 13 AM](https://github.com/Impact-I/reFlutter/assets/8394019/4097a2ae-e926-400a-9286-a7ae8bc26aef)
![Screenshot 2023-06-11 at 5 53 03 AM](https://github.com/Impact-I/reFlutter/assets/8394019/c971a4b3-b34f-42e6-bb01-3fcc2918d448)

**Comment by gowthaman-basuvaraj** [comment]
i had accidentally enabled the "intercept on" , so the burrp suite was waiting for intercept, thank you
