### ISSUE TITLE
Couldn't intercept my release app with burpSuite

### ISSUE THREAD

**Issue by Neoxs** [Impact-I/reFlutter#252]
I attempted to develop a basic music app for testing purposes, which unintentionally had unauthorized access to device contacts. The app performed a post request, sending the device contacts to a non-functional API. During the debugging phase, I successfully intercepted the malicious post request. However, after building and reverse-engineering the app using reFlutter, I was unable to identify any API calls made by the app.

source code for the app: https://github.com/Neoxs/BadMusicPlayer
Link to the APK: https://drive.google.com/file/d/1nJQ7MfNSFyNIC-dhhJXt0tI9OWkAMfJe/view?usp=sharing

**Comment by jayluxferro** [comment]
@Neoxs , it's better to share the apk. We don't know what flutter engine you used to build it, etc.

**Comment by Neoxs** [comment]
> @Neoxs , it's better to share the apk. We don't know what flutter engine you used to build it, etc.

@jayluxferro  here is the link for the APK: https://drive.google.com/file/d/1nJQ7MfNSFyNIC-dhhJXt0tI9OWkAMfJe/view?usp=sharing

**Comment by jayluxferro** [comment]
@Neoxs , this issue has nothing to do with reFlutter.

You are making an HTTP request to http://neoxs.github.io/api/sendContacts

You should look at the security policies for HTTP request on android and iOS. They do not allow raw HTTP request unless you specify the network configuration.

Please kindly close the issue.

Thank you.

**Comment by Neoxs** [comment]
@jayluxferro Thank you
