### ISSUE TITLE
Charles support

### ISSUE THREAD

**Issue by toman-tom** [Impact-I/reFlutter#253]
How can we get reFlutter to work with Charles proxy instead of Burp? Burp doesn't properly support HTTP2 responses (the headers are out of order for example).

I tried setting the IP in reFlutter to Charles but I have connectivity issues when using the app

**Comment by jayluxferro** [comment]
@toman-tom , I don't know what version of Burp you are using but it does support HTTP2.

![Screenshot 2023-06-14 at 7 28 06 PM](https://github.com/Impact-I/reFlutter/assets/8394019/b1b11939-cbfa-4de1-a814-9c7aa7146516)

I don't use Charles proxy so I cannot be of much help here. Probably someone can.
