### ISSUE TITLE
App works fine but still can't intercept any request?

### ISSUE THREAD

**Issue by palmmymumu** [Impact-I/reFlutter#254]
APK: https://drive.google.com/file/d/1cuqoP1tzr2YvOqrlpbw67eSXJK4VGfv0/view?usp=sharing

I use reflutter with option (1) then sign it with uber-apk-signer

After installed to the phone, app works fine, but still can't intercept any request in BurpSuite? (nothing happen)

**Comment by jayluxferro** [comment]
Hi @palmmymumu , please I suggest you raise issues that are related to reFlutter. You are using a go-binding in your app which is responsible for making the HTTP request in your test app. This has nothing to do with reFlutter. Please kindly close the issue.

thank you.


<img width="686" alt="Screenshot 2023-06-18 at 9 12 20 PM" src="https://github.com/Impact-I/reFlutter/assets/8394019/79092c9d-e84e-4353-ba33-9ab13ae60087">

<img width="734" alt="Screenshot 2023-06-18 at 9 07 40 PM" src="https://github.com/Impact-I/reFlutter/assets/8394019/eb616e7b-bc92-4072-87b7-36b9dba6c311">


```go
int type..eq.struct { MenuItemNumber int "json:\"menuItemNumber\""; AccountNumber string "json:\"accountNumber\""; AccountType string "json:\"accountType\""; AccountAliasName string "json:\"accountAliasName\""; AccountStatus string "json:\"accountStatus\""; DefaultAccountFlag string "json:\"defaultAccountFlag\""; MaskAccountFlag string "json:\"maskAccountFlag\""; ShowBalanceFlag string "json:\"showBalanceFlag\""; CardType interface {} "json:\"cardType\""; CardHolderFlag interface {} "json:\"cardHolderFlag\""; KecCardFlag interface {} "json:\"kecCardFlag\""; MainCustomerFlag interface {} "json:\"mainCustomerFlag\""; ESavingFlag string "json:\"eSavingFlag\""; ESavingStatus interface {} "json:\"eSavingStatus\""; AccumulatedAmount float64 "json:\"accumulatedAmount\""; LimitAmount float64 "json:\"limitAmount\""; ShowSmartPayMenuFlag string "json:\"showSmartPayMenuFlag\""; ShowSmartCashMenuFlag string "json:\"showSmartCashMenuFlag\""; ShowCardInfoFlag string "json:\"showCardInfoFlag\""; ShowWithdrawMenuFlag string "jso(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11) {
    do {
            var_16 = arg10;
            var_8 = arg9;
            r7 = arg7;
            if (&var_0 >= *(r28 + 0x10)) {
                break;
            }
            runtime.morestack_noctxt();
    } while (true);

```

**Comment by palmmymumu** [comment]
> 

Excuse me, but how did you intercept that?

**Comment by palmmymumu** [comment]
> Hi @palmmymumu , please I suggest you raise issues that are related to reFlutter. You are using a go-binding in your app which is responsible for making the HTTP request in your test app. This has nothing to do with reFlutter. Please kindly close the issue.
> 
> thank you.
> 
> <img alt="Screenshot 2023-06-18 at 9 12 20 PM" width="686" src="https://user-images.githubusercontent.com/8394019/246690994-79092c9d-e84e-4353-ba33-9ab13ae60087.png"> <img alt="Screenshot 2023-06-18 at 9 07 40 PM" width="734" src="https://user-images.githubusercontent.com/8394019/246690990-eb616e7b-bc92-4072-87b7-36b9dba6c311.png">
> ```go
> int type..eq.struct { MenuItemNumber int "json:\"menuItemNumber\""; AccountNumber string "json:\"accountNumber\""; AccountType string "json:\"accountType\""; AccountAliasName string "json:\"accountAliasName\""; AccountStatus string "json:\"accountStatus\""; DefaultAccountFlag string "json:\"defaultAccountFlag\""; MaskAccountFlag string "json:\"maskAccountFlag\""; ShowBalanceFlag string "json:\"showBalanceFlag\""; CardType interface {} "json:\"cardType\""; CardHolderFlag interface {} "json:\"cardHolderFlag\""; KecCardFlag interface {} "json:\"kecCardFlag\""; MainCustomerFlag interface {} "json:\"mainCustomerFlag\""; ESavingFlag string "json:\"eSavingFlag\""; ESavingStatus interface {} "json:\"eSavingStatus\""; AccumulatedAmount float64 "json:\"accumulatedAmount\""; LimitAmount float64 "json:\"limitAmount\""; ShowSmartPayMenuFlag string "json:\"showSmartPayMenuFlag\""; ShowSmartCashMenuFlag string "json:\"showSmartCashMenuFlag\""; ShowCardInfoFlag string "json:\"showCardInfoFlag\""; ShowWithdrawMenuFlag string "jso(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11) {
>     do {
>             var_16 = arg10;
>             var_8 = arg9;
>             r7 = arg7;
>             if (&var_0 >= *(r28 + 0x10)) {
>                 break;
>             }
>             runtime.morestack_noctxt();
>     } while (true);
> ```

 Excuse me, but how did you intercept that?

**Comment by jayluxferro** [comment]
@palmmymumu , there are several reverse engineering tools there for decompiling dex files.
