### ISSUE TITLE
 This engine is currently not supported.

### ISSUE THREAD

**Issue by arthusu** [Impact-I/reFlutter#255]
Engine SnapshotHash: de19b7dfc926ad13cc9f10c3d28d41fa

 This engine is currently not supported.
 Most likely this flutter application uses the Debug version engine which you need to build manually using Docker at the moment.
 More details: https://github.com/Impact-I/reFlutter

![image](https://github.com/Impact-I/reFlutter/assets/12725208/78e2f868-60c8-4cf1-aa33-5406a1300af3)

how can I solve this problem, I did not find the engine in the CSV table: https://github.com/Impact-I/reFlutter/blob/main/enginehash.csv

**Comment by jayluxferro** [comment]
The engine you have isn't in any flutter version ever released. You can check here: https://github.com/Impact-I/reFlutter/blob/main/scripts/enginehash.tmp.csv

Therefore you can't rebuild the engine.
