### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by Easy987** [Impact-I/reFlutter#258]
Hi,

I am trying to intercept and get dump of an application.

The application uses a HTTP request to log in by user, and after that it tries to connect to a TCP server.

I am using Burp, the HTTP request shows on the screen, returns with the correct data and lets me log in. However, while connecting to the TCP server the connection just hangs and i couldnt log in. Because of this, lots of dart pointer is not showing, because i am not seeing that widgets.

Somehow can i disable the proxy feature to be able to log in and get pointers, or somehow can i get the TCP connection running?

Thank you.

APK: https://drive.google.com/file/d/1Byjy9UcDIe_RCMFIYWicJHFPktcHVtfD/view?usp=drivesdk

**Comment by jayluxferro** [comment]
You need to manually comment out the network patch and build the engine manually.
