### ISSUE TITLE
This engine is currently not supported. Need Help. . .

### ISSUE THREAD

**Issue by cryptoexpertssss** [Impact-I/reFlutter#259]
![image](https://github.com/Impact-I/reFlutter/assets/101889698/382afca0-b62d-45a8-8687-995dccbe1e20)

![image](https://github.com/Impact-I/reFlutter/assets/101889698/3c230188-f8f7-4365-95f5-ddba39a5acda)

  <key>FlutterEngine</key>
  <string>b4fb11214dd2dda6ce012dd98ea498e9e8b91262</string>

How can I solve this problem, I did not find the engine in the CSV table: https://github.com/Impact-I/reFlutter/blob/main/enginehash.csv

**Comment by kluo84** [comment]
i have the same issue, not sure how to trace the root cause. Any idea?

**Comment by cryptoexpertssss** [comment]
@jayluxferro @Impact-I Need help . . . Please look into this

**Comment by kluo84** [comment]
I saw Jay responded in this thread https://github.com/Impact-I/reFlutter/issues/255. Basically, the engine is not in the csv. Not sure if we can patch the application to add the valid engine then re-run the reflutter.

**Comment by jayluxferro** [comment]
@cryptoexpertssss @kluo84  , I added a script that you can use to determine the flutter engine and cross reference with the https://github.com/Impact-I/reFlutter/blob/main/enginehash.csv


Steps:

1. Unzip the `.apk` file.
2. Locate the `libflutter.so` 
3. Now run
```
python3 scripts/get_flutter_engine.py [path_to_libflutter.so_file]
```

4. You should get the corresponding `engine commit hash` which maps to the actual `snapshot hash`
