### ISSUE TITLE
Install the IPA after reFlutter on iOS 14 and encounter the 'Incorrect Full Snapshot Version' error.

### ISSUE THREAD

**Issue by turingH** [Impact-I/reFlutter#266]
This is the console output:
```shell
SnapshotHash: aa64af18e7d086041ac127cc4bc50c5e
The resulting ipa file: ./release.RE.ipa
Please install the ipa file

Configure Burp Suite proxy server to listen on *:8083
Proxy Tab -> Options -> Proxy Listeners -> Edit -> Binding Tab

Then enable invisible proxying in Request Handling Tab
Support Invisible Proxying -> true
```

The app opens briefly and then immediately exits.
This is the console output of the app:
```shell
[VERBOSE-3:dart_vm_initializer.cc(89)] Error while initializing the Dart VM: Wrong full snapshot version, expected 'd0acff364c5b952c8b90ea5daf5982f6' found 'aa64af18e7d086041ac127cc4bc50c5e'
```
Is there a solution available for this type of issue?

**Comment by cryptoexpertssss** [comment]
@jayluxferro Bro need help. .. . I am also getting the same error

**Comment by jayluxferro** [comment]
@turingH , there's no snapshot hash `d0acff364c5b952c8b90ea5daf5982f6`

If you can share the ipa I can look into it.

You can find all the flutter snapshot hashes and the engine hashes here: https://github.com/Impact-I/reFlutter/blob/main/scripts/enginehash.tmp.csv

**Comment by cryptoexpertssss** [comment]
![image](https://github.com/Impact-I/reFlutter/assets/101889698/82103288-fa5d-489d-8198-b17d50ee0f24)
Bro please see the screenshot for reference... Sorry can't share the apk file. Its confidential.

**Comment by cryptoexpertssss** [comment]
![image](https://github.com/Impact-I/reFlutter/assets/101889698/1d46d407-11f0-4706-89f2-2dda6c000a56)

**Comment by cryptoexpertssss** [comment]
@jayluxferro See this logcat for ur reference .. .  and help solve this issue please

![image](https://github.com/Impact-I/reFlutter/assets/101889698/176ad750-84f6-4a59-9d61-2d2f91da5994)

**Comment by KDR9666** [comment]
I have done with reflutter, May I know how to resign to install the application on an IOS device?

![image](https://github.com/Impact-I/reFlutter/assets/57517371/fdeb2c22-456a-41c6-b5d2-8216209b26cf)

**Comment by jayluxferro** [comment]
Hi @KDR9666 

Use this https://github.com/DanTheMan827/ios-app-signer, to sign the IPA file and the install it using `ios-deploy`

**Comment by KDR9666** [comment]
Thanks!
I have reviewed it but couldn't find the correct steps to create a project. Additionally, I don't have access to Mac OS. Can you assist me with this?

It's very urgent for me, and I would be very grateful if you could help me successfully intercept the traffic using Burp.
