### ISSUE TITLE
reFlutter Traffic Intercept Issue

### ISSUE THREAD

**Issue by bloggerstesting** [Impact-I/reFlutter#269]
Hello Team,

Thanks for creating such an awesome tool for bypass the flutter SSL pinning.

Reflutter works well with Flutter which has REST APIs. Recently, I received an Android application created with Flutter + GRPC Protobuf API. I did the reflutter and signed the APK. The application works well and is able to intercept third party API calls. However, it is not able to intercept the GRPC Protobuf API calls. Android logcat displays the following error in command console:

**I : Flutter .dart Missing Trailers**

Please let me know if there is a solution to resolve this issue and successfully intercept GRPC traffic from android applications.

Thanks

**Comment by jayluxferro** [comment]
@bloggerstesting , can you share the application? if possible.

**Comment by bloggerstesting** [comment]
@jayluxferro  Sharing an application publicly is difficult for me. Is there any way to connect directly with you?
