### ISSUE TITLE
Tampered Alert

### ISSUE THREAD

**Issue by decoderid** [Impact-I/reFlutter#274]
# Intro
traffic works on burpsuite, but the app activity show alert, how to bypass this?

# Alert
![image](https://github.com/Impact-I/reFlutter/assets/75539501/e590a0e7-00e4-4e34-92b6-8fbe20178830)

# Traffic
![image](https://github.com/Impact-I/reFlutter/assets/75539501/027f2769-34ab-471b-9bf5-f38390d5a1a1)

**Comment by jayluxferro** [comment]
@decoderid , this isn't something reflutter can help you with. You need to find your own ways to do that.

Thank you.
