### ISSUE TITLE
Unable to get dump.dart of some apps snapshot 👇

### ISSUE THREAD

**Issue by ab47cp** [Impact-I/reFlutter#275]
Snapshothashes :- 

90b56a561f70cd55e972cb49b79b3d8b

And

7dbbeeb8ef7b91338640dca3927636de

**Comment by AbhiTheModder** [comment]
@ab47cp you should submit a PR with the changed snapshots.

**Comment by ab47cp** [comment]
No idea, can you give a tutorial on your telegram channel 🙂

**Comment by AbhiTheModder** [comment]
@ab47cp Fork the repo > Put the changes snapshots hash in [SNAPSHOT_HASH](https://github.com/Impact-I/reFlutter/blob/main/SNAPSHOT_HASH) and commit then raise a PR(pull request)

**Comment by ab47cp** [comment]
> @ab47cp Fork the repo > Put the changes snapshots hash in [SNAPSHOT_HASH](https://github.com/Impact-I/reFlutter/blob/main/SNAPSHOT_HASH) and commit then raise a PR(pull request) 

Okk I will try

**Comment by Happ1ness-dev** [comment]
> And
> 
> 7dbbeeb8ef7b91338640dca3927636de

Hello, I'm experiencing similar issues.
But besides not creating any dump, it doesn't even change permissions to the app's directory.
Same exact hash: `7dbbeeb8ef7b91338640dca3927636de`.

Maybe it's because I'm on termux, and I have to use some kind of distro instead. I'll let you know if I'd manage to fix it.

**Comment by Happ1ness-dev** [comment]
> Maybe it's because I'm on termux

Nope, it doesn't work in Ubuntu either.
I remember it working in the past though, about a year ago or so.

**Comment by Happ1ness-dev** [comment]
And it's not like I've set up the BurpSuite incorrectly. It's working fine and intercepting all http requests ¯⁠\⁠_⁠(⁠ツ⁠)_⁠/⁠¯

There's also a lib with that hash available now too, so I'm actually confused.

**Comment by Happ1ness-dev** [comment]
Ok, I found the solution, and it was surprisingly simple. 

It seems pip was installing the wrong version of reflutter somehow. 
Forcing it to install the package from this repo fixed the issue for me 😁

**Comment by AbhiTheModder** [comment]
> Ok, I found the solution, and it was surprisingly simple.
> 
> It seems pip was installing the wrong version of reflutter somehow. Forcing it to install the package from this repo fixed the issue for me 😁

@Happiness777 
Nice... Yes, as there has been many Pushes to git by the team maybe that had caused the issue.
