### ISSUE TITLE
Version 12 Dump support

### ISSUE THREAD

**Issue by palmarci** [Impact-I/reFlutter#278]
Hello, first of all thanks for this great project. Second of all, would it be possible to add dump support to version 12 (af51afceb8886cc11e25047523c4e0c7e1f5d408)? I have debugged your script and found out that there is this check which fails due to the files being unavailable:

`if os.path.exists("src/third_party/dart/runtime/vm/dart.cc") or os.path.exists("tools/generate_package_config/pubspec.yaml") or os.path.exists("DEPS"):
`
thanks

**Comment by jayluxferro** [comment]
Hi @palmarci , I'm working on the dump support. Will let you know once it's complete

**Comment by palmarci** [comment]
> Hi @palmarci , I'm working on the dump support. Will let you know once it's complete

thank you for the quick reply. i will be waiting anxiously
