### ISSUE TITLE
There was no libapp.so (Android) or App (iOS) found in the package.

### ISSUE THREAD

**Issue by r3dr0se952** [Impact-I/reFlutter#282]
Is this really a Flutter app?
There was no libapp.so (Android) or App (iOS) found in the package.

 Make sure there is arm64-v8a/libapp.so or App.framework/App file in the package. If flutter library name differs you need to rename it properly before patching.

reFlutter doesn't work with any app on me i installed on my macos with pip installer in ipa file i can clearly see libapp.so file what is problem tho?

**Comment by Flyy-yu** [comment]
Same issue here

**Comment by jayluxferro** [comment]
@radiosamurai @Flyy-yu , what was the hash that was displayed?

**Comment by r3dr0se952** [comment]
> @radiosamurai @Flyy-yu , what was the hash that was displayed?

hi i cannot see the hash i simply run reflutter com.test.ipa to console.


 Choose an option:

 1. Traffic monitoring and interception
 2. Display absolute code offset for functions

 [1/2]? 2

 This mode is only for dump and offset output, slow application operation is possible (network patch is still left)

Is this really a Flutter app?
There was no libapp.so (Android) or App (iOS) found in the package.

 Make sure there is arm64-v8a/libapp.so or App.framework/App file in the package. If flutter library name differs you need to rename it properly before patching.

**Comment by jayluxferro** [comment]
@radiosamurai then it's not a flutter App. When you unzip the ipa do you see `Flutter.framework` in the Framework folder? If not then it isn't a flutter app.

**Comment by r3dr0se952** [comment]
> @radiosamurai then it's not a flutter App. When you unzip the ipa do you see `Flutter.framework` in the Framework folder? If not then it isn't a flutter app.

yes i can see also there is app in here too

<img width="1309" alt="image" src="https://github.com/Impact-I/reFlutter/assets/104136919/0e421e80-cdc0-4d61-ac85-5f20af8b9674">

**Comment by jayluxferro** [comment]
@radiosamurai if you don't mind you can share the ipa and let me check. If the app is in debug mode then it won't work with reFlutter.

**Comment by r3dr0se952** [comment]
> @radiosamurai if you don't mind you can share the ipa and let me check. If the app is in debug mode then it won't work with reFlutter.

file is too big for github where i can share with you?

**Comment by jayluxferro** [comment]
@radiosamurai telegram

**Comment by r3dr0se952** [comment]
> @radiosamurai telegram

send ur username pls

**Comment by jayluxferro** [comment]
> > @radiosamurai telegram
> 
> send ur username pls

Same username as GitHub username

**Comment by r3dr0se952** [comment]
> > > @radiosamurai telegram
> > 
> > 
> > send ur username pls
> 
> Same username as GitHub username

i texted you

**Comment by jayluxferro** [comment]
@radiosamurai , you have an encrypted IPA. You need to install it on a jailbroken device and dump the decrypted IPA before you can use reFlutter.

You can use https://github.com/jayluxferro/frida-ios-dump to dump the decrypted IPA.

<img width="775" alt="Screenshot 2024-01-04 at 13 31 42" src="https://github.com/Impact-I/reFlutter/assets/8394019/56c7f0f1-50d5-4455-88ba-db6360e472e9">

**Comment by r3dr0se952** [comment]
> @radiosamurai , you have an encrypted IPA. You need to install it on a jailbroken device and dump the decrypted IPA before you can use reFlutter.
> 
> You can use https://github.com/jayluxferro/frida-ios-dump to dump the decrypted IPA.
> 
> <img alt="Screenshot 2024-01-04 at 13 31 42" width="775" src="https://private-user-images.githubusercontent.com/8394019/294193237-56c7f0f1-50d5-4455-88ba-db6360e472e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDUzMjUsIm5iZiI6MTcwNDQ0NTAyNSwicGF0aCI6Ii84Mzk0MDE5LzI5NDE5MzIzNy01NmM3ZjBmMS01MGQ1LTQ0NTUtODhiYS1kYjYzNjBlNDcyZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDg1NzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWMyMGY1NDliYmZlZjg2ODE2ZTdmOWQ2YjQxYzI5MjMwMjQ4NzE4M2VhNGI3NjYyMzg1N2YyM2VlOWYwMGRiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-RCtcn2MwNcX9sKMuWdtMSLonEC2lQ6ttcQEHqB0VKU">

hi i encrypted ipa and now app is closing with this hash :: f71c76320d35b65f1164dbaa6d95fe09

**Comment by jayluxferro** [comment]
> > @radiosamurai , you have an encrypted IPA. You need to install it on a jailbroken device and dump the decrypted IPA before you can use reFlutter.
> > You can use https://github.com/jayluxferro/frida-ios-dump to dump the decrypted IPA.
> > <img alt="Screenshot 2024-01-04 at 13 31 42" width="775" src="https://private-user-images.githubusercontent.com/8394019/294193237-56c7f0f1-50d5-4455-88ba-db6360e472e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDUzMjUsIm5iZiI6MTcwNDQ0NTAyNSwicGF0aCI6Ii84Mzk0MDE5LzI5NDE5MzIzNy01NmM3ZjBmMS01MGQ1LTQ0NTUtODhiYS1kYjYzNjBlNDcyZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDg1NzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWMyMGY1NDliYmZlZjg2ODE2ZTdmOWQ2YjQxYzI5MjMwMjQ4NzE4M2VhNGI3NjYyMzg1N2YyM2VlOWYwMGRiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-RCtcn2MwNcX9sKMuWdtMSLonEC2lQ6ttcQEHqB0VKU">
> 
> hi i encrypted ipa and now app is closing with this hash :: f71c76320d35b65f1164dbaa6d95fe09

@radiosamurai , possible issue might be that didn't sign the decrypted and patched IPA with a valid developer ID. You can consider using TrollStore depending on your iOS version or AppSync (https://github.com/akemin-dayo/AppSync).

**Comment by tianxiawoyougood** [comment]
Is it possible that the IPA generated by reflutter has a bug?

**Comment by tianxiawoyougood** [comment]
I used a dump IPA, then used reflutter to generate an IPA, and finally signed it myself, and it ran normally on the device. But there is no log. Is it possible that this is a bug in reflutter?
I can receive the log of the APP, but there is nothing about reflutter.

**Comment by gl4nce** [comment]
Same here. Can not find any `dart.dump` file in application folder on iOS.
