### ISSUE TITLE
  After repackaging, the app can run but cannot connect to the internet

### ISSUE THREAD

**Issue by Dyingchen** [Impact-I/reFlutter#284]
When I use reFlutter to repackage applications with the following version numbers
3.7.12 | 1a65d409c7a1438a34d21b60bf30a6fd5db59314 | adb4292f3ec25074ca70abcd2d5c7251

The app can run normally and generate dump. dart normally, but the app cannot connect to the internet(It is normal to connect to the internet without packaging), and many function bodies in the generated dump. dart have no content, as shown below:

![图片](https://github.com/Impact-I/reFlutter/assets/79223608/03b75b9f-4d48-4b42-8983-4c63863e2750)
![图片](https://github.com/Impact-I/reFlutter/assets/79223608/cf2710ca-431b-4c14-a2c0-3f1d3fef5a35)

As many of these names are meaningless, I would like to ask if this was caused by confusion among developers

Looking forward to the author's response 

 tks

**Comment by AbhiTheModder** [comment]
You should try option 2 for internet connection issue if that fixes it

**Comment by Dyingchen** [comment]
> You should try option 2 for internet connection issue if that fixes it



Because I don't need to analyze the app's traffic temporarily, I actually chose option 2. However, the program still requires me to enter the BP address, so I randomly entered an address. Is this the reason why the app cannot connect to the internet?

![图片](https://github.com/Impact-I/reFlutter/assets/79223608/edbaced1-eca6-41ff-9569-60955d244c66)

**Comment by jayluxferro** [comment]
@Dyingchen that's the reason. By the way what version of reFlutter are you using?

**Comment by Dyingchen** [comment]
> @Dyingchen that's the reason. By the way what version of reFlutter are you using?

adb4292f3ec25074ca70abcd2d5c7251

After comparing the hash table provided by the project, it was determined that

3.7.12 | 1a65d409c7a1438a34d21b60bf30a6fd5db59314 | adb4292f3ec25074ca70abcd2d5c7251

So the reflutter version I am using is 0.7.2

Also, the method I used to determine the version was to view the hash at libapp. so offset 0x214 through a binary editor

![图片](https://github.com/Impact-I/reFlutter/assets/79223608/76e388b3-714f-489f-8bea-dd7993e04c87)

When I opened libflutter.so using ida to search for version features, I found that its version features also correspond to libapp. so

**Comment by Dyingchen** [comment]
> @Dyingchen that's the reason. By the way what version of reFlutter are you using?



So I need to make the mobile phone running the app able to connect to BP's agent, so that the app can connect to the network correctly, right?

**Comment by AbhiTheModder** [comment]
> > @Dyingchen that's the reason. By the way what version of reFlutter are you using?
> 
> So I need to make the mobile phone running the app able to connect to BP's agent, so that the app can connect to the network correctly, right?

To achieve that, you can do one thing:
 - Turn on your Phone hotspot and connect to that hotspot in your PC/laptop
 - now you have same IP on both, just get IP of `wlan` through `ipconfig` and get it done with
 
 OR, you could use reflutter in your phone directly on the apk through Termux (Note that in Termux the command is `ifconfig` not `ipconfig` to get your IP`)

This will do the work of connecting to the internet if you don't want to use BP

**Comment by Dyingchen** [comment]
> > > @Dyingchen that's the reason. By the way what version of reFlutter are you using?
> > 
> > 
> > So I need to make the mobile phone running the app able to connect to BP's agent, so that the app can connect to the network correctly, right?
> 
> To achieve that, you can do one thing:
> 
>     * Turn on your Phone hotspot and connect to that hotspot in your PC/laptop
> 
>     * now you have same IP on both, just get IP of `wlan` through `ipconfig` and get it done with
> 
> 
> OR, you could use reflutter in your phone directly on the apk through Termux (Note that in Termux the command is `ifconfig` not `ipconfig` to get your IP`)
> 
> This will do the work of connecting to the internet if you don't want to use BP


Actually, what I mean is that I don't need to do traffic analysis, I just need to get the function name, but I will try it out

tks

**Comment by Dyingchen** [comment]
> > > @Dyingchen that's the reason. By the way what version of reFlutter are you using?
> > 
> > 
> > So I need to make the mobile phone running the app able to connect to BP's agent, so that the app can connect to the network correctly, right?
> 
> To achieve that, you can do one thing:
> 
>     * Turn on your Phone hotspot and connect to that hotspot in your PC/laptop
> 
>     * now you have same IP on both, just get IP of `wlan` through `ipconfig` and get it done with
> 
> 
> OR, you could use reflutter in your phone directly on the apk through Termux (Note that in Termux the command is `ifconfig` not `ipconfig` to get your IP`)
> 
> This will do the work of connecting to the internet if you don't want to use BP

It doesn't look great, I've tried various methods, but the app is mostly stuck on the startup page, occasionally jumping to a page without a network after a long period of time. I'm sure it's not the app checking the signature. But I am not sure if the issue with the app was caused by repackaging reFlutter or self checking the app itself. In short, due to various factors, this work can only be temporarily put on hold
