### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by ligmaSec** [Impact-I/reFlutter#290]
nothing happens when I try to run the program, I get the following and the program exits : 

 Choose an option: 

 1. Traffic monitoring and interception 
 2. Display absolute code offset for functions

 [1/2]? 1

Example: (192.168.1.154) etc.
Please enter your BurpSuite IP: 127.0.0.1

 Wait...

d1b9a6938ad77326ac3a94d92bbc77933ed829ed

**Comment by AbhiTheModder** [comment]
You've to enter your burpsuite IP not local i.e, `127.0.0.1` xD

Or you can put the ip of your same current network through which both android and your PC is connected, use `ipconfig` to get it.

**Comment by ligmaSec** [comment]
> You've to enter your burpsuite IP not local i.e, `127.0.0.1` xD
> 
> Or you can put the ip of your same current network through which both android and your PC is connected, use `ipconfig` to get it.

that's just an example, I've tried with the ip from which the android app can reach my pc too :/

**Comment by secureITmania** [comment]
"The reFlutter tool is only compatible with arm64 and arm32 architectures. Based on my understanding, it seems like you are attempting to use it on an x86_64 application."
