### ISSUE TITLE
Is it possible to use reflutter without internet connection for intercepting flutter traffic?

### ISSUE THREAD

**Issue by Khartheesvar** [Impact-I/reFlutter#291]
I am on a machine that has no internet connection. Is it possible to use reflutter to patch the apk on this machine without an active internet connection? 
![error](https://github.com/Impact-I/reFlutter/assets/57453077/27a1fa2a-1725-4f93-80db-b1ad8684bede)

**Comment by jayluxferro** [comment]
@Khartheesvar ,

Reflutter needs to download the re-packaged flutter engines. Check the implementation.
