### ISSUE TITLE
Reflutter not working

### ISSUE THREAD

**Issue by BotVasu** [Impact-I/reFlutter#298]
It is giving me a huge error. It says that self.sock = self._create_connection() isnt working.
As i select the Trafiic monitoring option it fails to reflutter the app.
 Choose an option:

 1. Traffic monitoring and interception
 2. Display absolute code offset for functions

 [1/2]? 1

I have the latest release of the application as well.

![image](https://github.com/user-attachments/assets/1eb2499d-2404-4a46-8338-f7fa7680e867)

**Comment by jayluxferro** [comment]
Hi @BotVasu ,

This isn't an issue of reFlutter. Please check your internet connection and make sure you can access GitHub using your current internet connection. It needs Internet access to download the Flutter engine.

**Comment by BotVasu** [comment]
Hi @jayluxferro ,

May I know which part of GitHub is being accessed in the code and even though it needs the flutter engine. May I know what is the specified domain to fetch the results for the same?
So that I cross check from my side as well.

**Comment by jayluxferro** [comment]
Hi @BotVasu ,

Please check the reflutter code. 

[def networkLib():](https://github.com/Impact-I/reFlutter/blob/main/src/__init__.py#L67)

So make sure your device has internet access when using reFlutter.

**Comment by BotVasu** [comment]
Hey @jayluxferro ,

Thanks. Will do check and try again.
