### ISSUE TITLE
increase flutter version

### ISSUE THREAD

**Issue by 123456789zws** [Impact-I/reFlutter#301]
please support 3eda3cd112d4dbe04d80281af1ee5708，thank you

**Comment by jayluxferro** [comment]
@123456789zws 

which flutter version has that hash? There's no flutter version with that hash.

**Comment by 123456789zws** [comment]
I'm sorry,&nbsp;I couldn't express the problem clearly.




&nbsp;I use reflutter get output:&nbsp;&nbsp;




This mode is only for dump and offset output, slow application operation is pos
sible (network patch is still left)


&nbsp;Engine SnapshotHash: 3eda3cd112d4dbe04d80281af1ee5708


&nbsp;This engine is currently not supported.
&nbsp;Most likely this flutter application uses the Debug version engine which you ne
ed to build manually using Docker at the moment.
&nbsp;More details: https://github.com/Impact-I/reFlutter





I use blutter get dart output:
Dart version: 3.3.4, Snapshot: 3eda3cd112d4dbe04d80281af1ee5708, Target: android
&nbsp;arm64



In order to analysys the problem clearyly, Due to the file being too large I am sending that app address in zip file. I hope you analysys it，thank you.







                       
原始邮件
                       
                     

发件人："Jay"< ***@***.*** &gt;;

发件时间：2024/8/21 15:40

收件人："Impact-I/reFlutter"< ***@***.*** &gt;;

抄送人："123456789zws"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [Impact-I/reFlutter] increase flutter version (Issue #301)




 
Closed #301 as completed.
