### ISSUE TITLE
Reflutter didn't generate an apk

### ISSUE THREAD

**Issue by Zainmansour** [Impact-I/reFlutter#305]
when I use reflutter it didn't generate a new apk to install and use , 

when I use it it says wait and instade of giving me a snapshot hash and the resulting apk 
the progess ends and gives me diffirent outputs like:
04817c99c9fd4956f27505204f7e344335810aed

74d16627b940bb15e50891f82cad6c3e3465bd6d

is it a bug?

**Comment by jayluxferro** [comment]
@Zainmansour it's not a bug. Make sure you have internet access when using it.

**Comment by Zainmansour** [comment]
I am sure that my internet is so good and fast
also I tried it with and without vpn but the same problem appears

**Comment by jayluxferro** [comment]
> I am sure that my internet is so good and fast also I tried it with and without vpn but the same problem appears

It needs to be able to download the enginehash.csv (https://raw.githubusercontent.com/Impact-I/reFlutter/refs/heads/main/enginehash.csv) file. 

If it misses that then it’ll fail.

**Comment by jayluxferro** [comment]
If it persists you can share the apk if possible.

**Comment by Zainmansour** [comment]
I've just tried with another apk 
when the progess ended, it gives me the same output : just a random string  , I opened the working directory and I found a folder called release and the enginehash.csv file but there is no apk

**Comment by Zainmansour** [comment]
@jayluxferro 
hey , this is what I mean

![SmartSelect_20241006-162821_Termux](https://github.com/user-attachments/assets/63ab6365-adbb-41e2-8e99-d1ebb1833f36)
![SmartSelect_20241006-162847_MT Manager](https://github.com/user-attachments/assets/6acbd8c3-17e5-43fb-aaf6-41d136838a70)

**Comment by jayluxferro** [comment]
> @jayluxferro hey , this is what I mean
> 
> ![SmartSelect_20241006-162821_Termux](https://private-user-images.githubusercontent.com/86538152/373950477-63ab6365-adbb-41e2-8e99-d1ebb1833f36.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjIwMDYsIm5iZiI6MTcyODIyMTcwNiwicGF0aCI6Ii84NjUzODE1Mi8zNzM5NTA0NzctNjNhYjYzNjUtYWRiYi00MWUyLThlOTktZDFlYmIxODMzZjM2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDEzMzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwN2EzOWRjZjExNjc2NTkxMWQ4ZmFhOGZhYzljMTc3YjYyZmIyNjFiMTQzOTQ1ZjFkZmZiZGQ5YzM2Y2IzMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eF0HteAi9mlc7m7EzP-h5MzaMnpdyR4xLwUYOY-_nHs) ![SmartSelect_20241006-162847_MT Manager](https://private-user-images.githubusercontent.com/86538152/373950481-6acbd8c3-17e5-43fb-aaf6-41d136838a70.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjIwMDYsIm5iZiI6MTcyODIyMTcwNiwicGF0aCI6Ii84NjUzODE1Mi8zNzM5NTA0ODEtNmFjYmQ4YzMtMTdlNS00M2ZiLWFhZjYtNDFkMTM2ODM4YTcwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDEzMzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOTA3ZjczNjQ0ZmQ4MDk1ZTNjYWZiNjgyMzg1Yzg4YjMxN2I1OTU0ZWQ4OTM5NTNmY2RkMTIzN2ZhZjJhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aW0cBKJpMTMHtzJCsxb4Y9KZOE1I9krmDInkeaeRsy0)

What environment are you using? Termux?

**Comment by jayluxferro** [comment]
@Zainmansour , I realized you're using Termux. Maybe your environment is restrictive. Can you try running it on an actual OS like windows, linux or macOS?

There's an issue like that here: https://github.com/Impact-I/reFlutter/issues/294

**Comment by jayluxferro** [comment]
@Zainmansour , I tried the same thing on Termux (Android) and it works.

![Screenshot 2024-10-06 at 14 06 43](https://github.com/user-attachments/assets/e8a1d873-d76f-4fb5-a88d-c4017e99f7d4)
![Screenshot 2024-10-06 at 14 09 45](https://github.com/user-attachments/assets/c4a3a3e3-1501-4c46-9ec7-cd4975e1907b)

**Comment by Zainmansour** [comment]
@jayluxferro 
hmm it is weird, what version of termux you've tried?

**Comment by jayluxferro** [comment]
> @jayluxferro hmm it is weird, what version of termux you've tried?

https://github.com/termux/termux-app/releases/tag/v0.118.1

**Comment by Zainmansour** [comment]
@jayluxferro 
I am using the same version 🤯
I'll try on windows

**Comment by Zainmansour** [comment]
@jayluxferro  tried on windows , same problem .
do you think it is because of apk is not possible to dump it or the developer did smt to prevent reverse engineering on his app? 
 
![20241006_190914](https://github.com/user-attachments/assets/e093c923-9cc1-403d-bf21-847f7ffd9343)

**Comment by jayluxferro** [comment]
> @jayluxferro tried on windows , same problem . do you think it is because of apk is not possible to dump it or the developer did smt to prevent reverse engineering on his app?
> 
> ![20241006_190914](https://private-user-images.githubusercontent.com/86538152/373961718-e093c923-9cc1-403d-bf21-847f7ffd9343.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzE2MjksIm5iZiI6MTcyODIzMTMyOSwicGF0aCI6Ii84NjUzODE1Mi8zNzM5NjE3MTgtZTA5M2M5MjMtOWNjMS00MDNkLWJmMjEtODQ3ZjdmZmQ5MzQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE2MTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTg4ZjQxYzFkZWUxZjU1OGY1MzUxMGVjNzYxMDA2MjA0NWFiNmQ5YzZhMmU4YWU0YjQ1MzdlYjc1YjBlMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WOZEhS787YKX5zNUnYfRvcKP2SmQ9J00eXKYxnb0_yE)

Probably. You should check if there are any such protections. You can share the apk too.

**Comment by Zainmansour** [comment]
@jayluxferro 
hey 
 can you please try out this apk :
https://t.me/apkreflutter/2

**Comment by jayluxferro** [comment]
> @jayluxferro hey can you please try out this apk : https://t.me/apkreflutter/2


@Zainmansour , it worked.
<img width="489" alt="Screenshot 2024-10-07 at 19 26 08" src="https://github.com/user-attachments/assets/ccb98663-9fe6-4772-a04e-018ff864912d">

**Comment by Zainmansour** [comment]
@jayluxferro 
hmm it is so weird,
I used this apk on my : 
• termux on android armeabi-v7a
• windows 10 with diffirent python version
is there anything I can try or I should close this issue and give up ?

**Comment by jayluxferro** [comment]
> @jayluxferro hmm it is so weird, I used this apk on my : • termux on android armeabi-v7a • windows 10 with diffirent python version is there anything I can try or I should close this issue and give up ?

Try: use `pip` or `pip3` depending on your default python

```
pip3 install reflutter==0.7.9
```

**Comment by Zainmansour** [comment]
@jayluxferro 
in this version ( 0.7.9 ) it stuck here : 
![SmartSelect_20241007-233712_Termux](https://github.com/user-attachments/assets/1c69b363-8157-40be-a3d4-0f025fc4644a)

but I tried to add some line to know where the code goes and here what I got ( this was in  verison 0.7.8) : 
![SmartSelect_20241007-224648_Termux](https://github.com/user-attachments/assets/b64445be-7c08-4830-b927-9abf27f4593d)

the numbers refers to the current line of 
__init__.py

**Comment by jayluxferro** [comment]
> @jayluxferro in this version ( 0.7.9 ) it stuck here : ![SmartSelect_20241007-233712_Termux](https://private-user-images.githubusercontent.com/86538152/374323455-1c69b363-8157-40be-a3d4-0f025fc4644a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMzQ0MDAsIm5iZiI6MTcyODMzNDEwMCwicGF0aCI6Ii84NjUzODE1Mi8zNzQzMjM0NTUtMWM2OWIzNjMtODE1Ny00MGJlLWEzZDQtMGYwMjVmYzQ2NDRhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIwNDgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZDg1ZTg1YmRkYWMwMDcxNDk5ZGU0OTRhZGNhMDg0OTU0NjU2YTY5YjM5NGI2ZjBjMDIxMjM0ZmI1ZjJlODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-0RWxB67Z9KIIHgj_9A8kEZASlmjE2T93h_DIYxL0oY)
> 
> but I tried to add some line to know where the code goes and here what I got ( this was in verison 0.7.8) : ![SmartSelect_20241007-224648_Termux](https://private-user-images.githubusercontent.com/86538152/374323829-b64445be-7c08-4830-b927-9abf27f4593d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMzQ0MDAsIm5iZiI6MTcyODMzNDEwMCwicGF0aCI6Ii84NjUzODE1Mi8zNzQzMjM4MjktYjY0NDQ1YmUtN2MwOC00ODMwLWI5MjctOWFiZjI3ZjQ1OTNkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIwNDgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYjhhZGEzZjJkNGE2MjIxMzFhMDhkMGVmMWM2MDgwZDQxYmRjZmFkMjYxYTY2NTE4NzAxMzJlN2Y2Y2MyNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8lfGoyYr8wcA7soaehfQ1RW9M1LPrMFk2oyjO-ur-5Q)
> 
> the numbers refers to the current line of **init**.py

That's what I used. Previous version still works. If you can debug what the issue is at your end then that'll be cool. 'cos I can't replicate it.

**Comment by Zainmansour** [comment]
@jayluxferro 
Ok I will try to debug it
thank you for your help 
and I'm sorry for wasting  your time.

**Comment by jayluxferro** [comment]
> @jayluxferro Ok I will try to debug it thank you for your help and I'm sorry for wasting your time.

You're welcome @Zainmansour

**Comment by Zainmansour** [comment]
@jayluxferro 
hey ,
I fixed it and generated an apk and it is good.
But there is an apk I used reflutter option 1 to capture its traffic but when I installed the apk it shows like there is no internet access 
is there any solution fo this?

**Comment by jayluxferro** [comment]
> @jayluxferro hey , I fixed it and generated an apk and it is good. But there is an apk I used reflutter option 1 to capture its traffic but when I installed the apk it shows like there is no internet access is there any solution fo this?

@Zainmansour 
Please share the snapshot hash or even better the apk.

**Comment by Zainmansour** [comment]
@jayluxferro 
here is the app: 

https://play.google.com/store/apps/details?id=net.betateam.app
