### ISSUE TITLE
Dump.dart not generated

### ISSUE THREAD

**Issue by Saul5662** [Impact-I/reFlutter#307]
Hello,

I am currently trying to dump the offsets from an app.

Snapshot Hash: `80a49c7111088100a233b2ae788e1f48`
reFlutter Version: `0.7.9`

Lib from app (for my arch): [LIB-arm64-v8a.zip](https://github.com/user-attachments/files/17355817/LIB-arm64-v8a.zip)

The snapshot hash is the same as #302 

reFlutter was used on device using termux and ALSO tested on an x64 machine. Both built the apk fine but failed to generate the dump.

`logcat -e reFlutter` shows nothing at all
`logcat -e Dart` shows some application related errors but nothing related to reFlutter (can be posted if needed)

Lmk if you need anymore details.

**Comment by Saul5662** [comment]
Adding to this. Could it be because the apk was split? I did antisplit it before running reFlutter.

**Comment by Saul5662** [comment]
UPDATE: Tried just patching the libraries apk and that failed too so its not due to apk splitting haha. Just wanted to rule that out. App runs fine just doesnt generate the dump.

**Comment by Saul5662** [comment]
Just checking in real quick, any progress?

**Comment by jayluxferro** [comment]
> Just checking in real quick, any progress?

@RealCalumPlays , fix in progress. will test and update you.

**Comment by Saul5662** [comment]
> > Just checking in real quick, any progress?
> 
> @RealCalumPlays , fix in progress. will test and update you.

No problem, thank you!

**Comment by jayluxferro** [comment]
@RealCalumPlays try with `reflutter v0.8.0`

**Comment by Saul5662** [comment]
> @RealCalumPlays try with `reflutter v0.8.0`

Will do ASAP.

**Comment by Saul5662** [comment]
> @RealCalumPlays try with `reflutter v0.8.0`

Can confirm that dump.dart is generated (for some reason on android 14 I cant read it; unrooted phone) but on my rooted phone its there fine. Thanks for your work!

**Comment by Saul5662** [comment]
Just another quick question. Is it possible to have a version WITHOUT traffic monitoring? It is causing issues with the app I am trying to inspect.

**Comment by jayluxferro** [comment]
> Just another quick question. Is it possible to have a version WITHOUT traffic monitoring? It is causing issues with the app I am trying to inspect.

Hmmm unless you modify the code and build the engine manually.

**Comment by Saul5662** [comment]
> > Just another quick question. Is it possible to have a version WITHOUT traffic monitoring? It is causing issues with the app I am trying to inspect.
> 
> Hmmm unless you modify the code and build the engine manually.

Yeah I am not the most knowledgeable on how reFlutter works but I commented out socket stuff so I will see if that works on my fork.

EDIT: This worked for my specific use case. Thats all from me now.
