### ISSUE TITLE
Unsupported Engine Version for Traffic Monitoring in reFlutter

### ISSUE THREAD

**Issue by Fusion-Parth** [Impact-I/reFlutter#311]
### Description
I'm attempting to use reFlutter to analyze the `dev.apk` file, but I encountered an error indicating that the current engine version is not supported. The output states:

'''
Engine SnapshotHash: 33333333333333333333333333333333
This engine is currently not supported.
Most likely this flutter application uses the Debug version engine which you need to build manually using Docker at the moment.
'''

I have followed the instructions from the repository to build the debug version of the Flutter engine using Docker but am still facing issues.

### Steps Taken:
1. Downloaded the APK file.
2. Ran `reflutter dev.apk`.
3. Selected option 1 for traffic monitoring.
4. Encountered the unsupported engine version error.

### Environment:
- OS: Windows 11
- reFlutter version: 0.7.9

Could anyone provide guidance on how to resolve this issue, or indicate if there are specific versions of the Flutter engine that are compatible with reFlutter? Thank you!

**Comment by jayluxferro** [comment]
@Fusion-Parth 

The current engine hash has been tampered with.

Try these scripts and you can use that to figure out what the actual engine version is

https://github.com/Impact-I/reFlutter/tree/main/scripts

```
get_flutter_engine.py -> Get flutter engine hash from a Flutter engine binary.
get_snapshot_hash.py -> Get app hash from App or libapp.so file.
```
