### ISSUE TITLE
Picking different snapshot

### ISSUE THREAD

**Issue by abramann** [Impact-I/reFlutter#312]
~~The flutter engine hash for this apk is `e8e40f5ed22cd36b043badae24ca01b40990cdd2`
reflutter picks snapshot hash `80a49c7111088100a233b2ae788e1f48`~~
the app works after patching but doesn't produce dump.dart.
https://gofile.io/d/eOBIaa
EDIT: I was wrong about different hash but the patched library doesn't produce dump.dart

**Comment by jayluxferro** [comment]
@abramann 

Try with `reflutter v0.8.0`
