### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by bayuaz** [Impact-I/reFlutter#313]
Hello,

I installed reflutter with: 
```
pip3 install reflutter==0.8.0
```
I got an error when run reflutter on Kali:
```
└─$ reflutter ~/Downloads/tes.apk                     
Traceback (most recent call last):
  File "/home/khatulistiwa/.local/bin/reflutter", line 5, in <module>
    from src.__init__ import main
ModuleNotFoundError: No module named 'src'
```
How to solve it?

**Comment by jayluxferro** [comment]
> Hello,
> 
> I installed reflutter with:
> 
> ```
> pip3 install reflutter==0.8.0
> ```
> 
> I got an error when run reflutter on Kali:
> 
> ```
> └─$ reflutter ~/Downloads/tes.apk                     
> Traceback (most recent call last):
>   File "/home/khatulistiwa/.local/bin/reflutter", line 5, in <module>
>     from src.__init__ import main
> ModuleNotFoundError: No module named 'src'
> ```
> 
> How to solve it?

@bayuaz ,

I have no idea what is wrong at your side. Tested the same thing on Kali and it works fine.
<img width="633" alt="Screenshot 2024-11-01 at 08 15 18" src="https://github.com/user-attachments/assets/657ca391-2099-4aa1-8fc0-cda447c6aec9">

**Comment by bayuaz** [comment]
I installed it inside python venv. If I install it outside, it works. Thanks for the solution @jayluxferro
