### ISSUE TITLE
http 包 网址是127.0.0.1 ?

### ISSUE THREAD

**Issue by newdream2017** [Impact-I/reFlutter#34]
抓到包为啥都是127.0.0.1 开头的，如何解决？
![image](https://user-images.githubusercontent.com/33240641/163925621-82c521be-e539-425f-8181-cd96398cc7d1.png)

**Comment by Impact-I** [comment]
Hi @newdream2017,

Thanks for your interest in the project! 
What ip is specified in ip field?

Apparently this is a feature of your application. It looks like it's addressing `127.0.0.1` you can check the proxy settings (BurpSuite) again and redirect to your host or create a rule to replace the Host header.
