### ISSUE TITLE
I'm not able to intercept the traffics of debug mode enable apk using reflutter

### ISSUE THREAD

**Issue by ghost** [Impact-I/reFlutter#35]
Hello reflutter team,
Can you please help me to intercept the traffic of debug mode enable apk using reflutter? 

Thanks

**Comment by Impact-I** [comment]
Hi @basant-karki ,
Thank you for your interest in the project!

What do you mean by debug mode?
To capture traffic you can follow the documentation.

`reflutter main.apk`
`input ip`
`sign and install apk`
`Configure Burp Suite proxy server to listen on *:8083`
`Proxy Tab -> Options -> Proxy Listeners -> Edit -> Binding Tab`
`Support Invisible Proxying -> true`

**Comment by ghost** [comment]
This is what i'm talking about, How can i solve this problem?
![thumbnail_outlook-xeccgdiap-aaaaaaaaaaaaa](https://user-images.githubusercontent.com/60461905/165027576-d6358e55-6713-472f-b707-f41329a16a4b.png)

**Comment by Impact-I** [comment]
@basant-karki , Your engine version is Debug.
They are currently not supported.
You can try compiling the engine yourself using Docker

**Comment by ghost** [comment]
do you have any supported video or reference? how to compile the engine?

**Comment by dgrivera** [comment]
> do you have any supported video or reference? how to compile the engine? 

Bump on this, only have few ideas about this.
