### ISSUE TITLE
How to hook the method

### ISSUE THREAD

**Issue by fencerj** [Impact-I/reFlutter#36]

**Comment by Impact-I** [comment]
The resulting offset from the dump can be used in the frida [script](https://github.com/Impact-I/reFlutter/blob/main/frida.js)

`frida -U -f <package> -l frida.js --no-pause`

**Comment by fencerj** [comment]
### 1. I already have get the dump.dart on apk. 
<img width="659" alt="image" src="https://user-images.githubusercontent.com/787174/164604961-e1867c01-f3fe-46d5-b76c-f59813d37a02.png">


### 2. Then I use the 010Edit find base address with search

<img width="664" alt="image" src="https://user-images.githubusercontent.com/787174/164604728-287df7aa-e68c-46a3-99ab-d45092915507.png">

### 3. And i use the fridajs try to hook method.
<img width="580" alt="image" src="https://user-images.githubusercontent.com/787174/164604941-402d1b7f-1999-4da6-b5d6-ed07eb032d41.png">


### 4. But I got some error like this..
![image](https://user-images.githubusercontent.com/787174/164604978-5811bf00-ccdc-46ae-ad60-3ded6fd7fcc3.png)

## What should I do next? How to write frida script？

**Comment by Impact-I** [comment]
Try using the frida script found in the [repository](https://github.com/Impact-I/reFlutter/blob/main/frida.js)

Add two numbers _kDartIsolateSnapshotInstructions + code offset

Write the resulting value to the `dumpOffset` variable

It seems you have the wrong value for _kDartIsolateSnapshotInstructions

**Comment by fencerj** [comment]
> Try using the frida script found in the [repository](https://github.com/Impact-I/reFlutter/blob/main/frida.js)
> 
> Add two numbers _kDartIsolateSnapshotInstructions + code offset
> 
> Write the resulting value to the `dumpOffset` variable

Thank you for your reply. 
I use change the address  in the frida.js  set the `dumpOffset` with `0x701516 `+ `0x0000000000126b64` = ` 0x71407A`
<img width="715" alt="image" src="https://user-images.githubusercontent.com/787174/164609659-61df3379-ac4a-445d-9b83-219e41da0a87.png">

But I got this error
![image](https://user-images.githubusercontent.com/787174/164611602-2125cc47-af12-4db4-b046-4bb16ec2abe8.png)

Did I find the wrong _kDartIsolateSnapshotInstructions address ? And how can I find Correct value?( I use 010Edit search keyword)
<img width="494" alt="image" src="https://user-images.githubusercontent.com/787174/164608849-1f554cd4-ef5e-4a4c-ba84-1b2411649cf5.png">

**Comment by Impact-I** [comment]
@fencerj ,
To get the value for `_kDartIsolateSnapshotInstructions`
you can use `readelf -Ws libapp.so`
Where is the value you need in the `Value` field

ex. `000000000000b000`
+
`0000000000126b64`

Thanks!

**Comment by fencerj** [comment]
> @fencerj , To get the value for `_kDartIsolateSnapshotInstructions` you can use `readelf -Ws libapp.so` Where is the value you need in the `Value` field
> 
> ex. `000000000000b000` + `0000000000126b64`
> 
> Thanks!

Thanks! I solved it.

**Comment by Impact-I** [comment]
@fencerj , Fine. Could you tell how you did it?

**Comment by fencerj** [comment]
@Impact-I According to your suggestion. I use `readelf -Ws libapp.so` find the correct address. Solved the problem.

**Comment by pythonName** [comment]
> 

hey，but how to get the value of _kDartIsolateSnapshotInstructions for App.framework on IOS??

**Comment by pythonName** [comment]
> @fencerj , To get the value for `_kDartIsolateSnapshotInstructions` you can use `readelf -Ws libapp.so` Where is the value you need in the `Value` field
> 
> ex. `000000000000b000` + `0000000000126b64`
> 
> Thanks!

hey，but how to get the value of _kDartIsolateSnapshotInstructions for App.framework on IOS??

**Comment by ghost** [comment]
> @Impact-I According to your suggestion. I use `readelf -Ws libapp.so` find the correct address. Solved the problem.

i got this . i m trying to find string used to encrypt
RETURN : 0x7a00008041
Argument 0 address 0x7a00008041 buffer: 150

 Value:
00000000  01 96 00 db 07 00 00 41 80 00 00 41 80 00 00 18  .......A...A....
00000010  01 39 00 14 0d 00 00 00 80 00 00 41 80 00 00 38  .9.........A...8
00000020  01 39 00 cf 04 00 00 01 80 00 00 41 80 00 00 38  .9.........A...8
00000030  01 39 00 d5 04 00 00 00 80 00 00 41 80 00 00 18  .9.........A....
00000040  06 05 00 ef 14 00 00 e1 e4 00 00 41 80 00 00 41  ...........A...A
00000050  80 00 00 41 80 00 00 41 80 00 00 41 80 00 00 41  ...A...A...A...A
00000060  80 00 00 41 80 00 00 41 80 00 00 41 80 00 00 41  ...A...A...A...A
00000070  80 00 00 41 80 00 00 41 80 00 00 05 00 00 00 00  ...A...A........
00000080  00 00 00 2c 00 00 00 18 00 00 00 ff ff ff ff fe  ...,............
00000090  ff ff ff 41 80 00                                ...A..
