### ISSUE TITLE
App cannot be opened  on Android

### ISSUE THREAD

**Issue by xjasonlyu** [Impact-I/reFlutter#37]
I followed the instructions from README and use uber-apk-signer to make the apk aligned and signed.

The apk was installed successfully. However, when I tried to open it, it crashed immediately.

So, I wonder why and what should I do to fix it.🤔

**Comment by Impact-I** [comment]
Hi @xjasonlyu ,
Thanks for your interest in the project!

What is your snapshot hash?
Can you share the apk file?

**Comment by xjasonlyu** [comment]
Hi, I'm new to Android RE, so I don't know what's the snapshot hash though.

The original apk file can be downloaded at [here](https://github.com/bdvajstudio/javdb/releases/download/app/javdb_android_v1.9.9.apk), and my refluttered version is uploaded at [here](https://file.io/0MuhyvIr3qTR).

Please noted that this apk contains NSFW content and I also don't know the safety about it.

**Comment by Impact-I** [comment]
@xjasonlyu ,
It's not a reFlutter problem

Pay attention to the LogCat output
The application contains `libsecurity.so` library
Looks like the `com.example.astarte.SecurityUtil.getSecret` method is being called
Then an exception is thrown and the application crashes.

**Comment by xjasonlyu** [comment]
Thanks for your time to debug it for me.

Hmm, I don't know about the mechanism of `libsecurity.so`, so I guess I should probably figure another way out.

FYI, my first attempt is the ipa version of this app on iOS device instead of the apk one, and it was reFluttered well. Then I opened it and saw the HTTP requests in Burp (but it requires CA installed anyway).

However, I saw a lot of reflutter dump.dart info in the console but I failed to pull the file from its Container - it's just not in there. Also, it seems not feasible to get the value of `_kDartIsolateSnapshotInstructions` via readefl since it's not EFL format in ipa.

I know it's not quite related to this Android issue, but I think I should mention it before I forgot lol.

**Comment by Impact-I** [comment]
_but it requires CA installed anyway_
Yes it is required on ios

_I saw a lot of reflutter dump.dart info in the console but I failed to pull the file from its Container_
That is, you got path to file (dump.dart) but did not find the file itself?

_readefl since it's not EFL format in ipa_
Yes, on ios you need to find the value of `_kDartIsolateSnapshotInstructions` via Ghidra/Hopper

It is strange that the ipa version is launched, perhaps there is no security mechanism.

This is helpful, thanks for letting me know

**Comment by xjasonlyu** [comment]
> _but it requires CA installed anyway_ 
> Yes it is required on ios

I didn't find this instruction on the README, so I was confused for a while.😂

> _I saw a lot of reflutter dump.dart info in the console but I failed to pull the file from its Container_
> That is, you got path to file (dump.dart) but did not find the file itself?

Yeah, it prints the dump.dart path to the console like `/private/var/mobile/Containers/Data/Application/xxxxx/dump.dart`, but I didn't see anything on app Container or the downloaded container .xcappdata file. 

Maybe I was doing it in the wrong way, if so what is the correct way to do the `Next, you will need to pull the file from the device` step?

Also I'm little confused about what's the right package name for `frida -U -f <package> -l frida.js --no-pause` when I use it on iOS, is it the process name?

**Comment by vividmuse** [comment]
> 

You can use reflutter to dump then use the original to hook with frida.  I succeeded  got it.
