### ISSUE TITLE
use apktool to rebuild the apk, crash

### ISSUE THREAD

**Issue by HuChundong** [Impact-I/reFlutter#40]
1. use reflutter and uber-apk-signer-1.2.1.jar
app will not work. the apk build lost some xmls.

2. use apktool to depack and replace libflutter, and repack, crash too. and log is below.
https://mumu.nie.netease.com/api/filepicker/APPCrashLog/logcat/2022-04-29/uQHpAvUvn51zgOlj.txt

some days ago, i can use the old version to reflutter the same app(same version). so i think the new reflutter broke something

**Comment by Impact-I** [comment]
Hi @HuChundong ,
The application crashes because of this `FORTIFY: strcat: prevented write past end of buffer`

Looks like a critical bug, I'll try to reproduce it.
Thanks!

**Comment by Impact-I** [comment]
@HuChundong , Can you share the apk file with us?

**Comment by Impact-I** [comment]
@HuChundong , Fixed for version `9cf77f4405212c45daf608e1cd646852`

**Comment by HuChundong** [comment]
> @HuChundong , Fixed for version `9cf77f4405212c45daf608e1cd646852`

thanks, i will test it

**Comment by Impact-I** [comment]
Updated https://github.com/Impact-I/reFlutter/releases/tag/android-v2-9cf77f4405212c45daf608e1cd646852

**Comment by Impact-I** [comment]
Solved!
