### ISSUE TITLE
IOS app is automatically closing after using reflutter

### ISSUE THREAD

**Issue by ghost** [Impact-I/reFlutter#48]
Hello team @Impact-I ,
After using your reflutter, my IPA is automatically closing after the start. But it does work without using reflutter. What could be the reason behind it?

Thanks for your help in advance.

**Comment by jayluxferro** [comment]
Hi @Impact-I , I am also experiencing the same issue when I used the updated version yesterday.

**Comment by ghost** [comment]
@jayluxferro which version are you using?

**Comment by jayluxferro** [comment]
@basant-karki version==0.6.6

**Comment by ghost** [comment]
@jayluxferro @Impact-I it works on "reflutter==0.4.9". But it keep crashing on the latest version. @Impact-I Please fix this issue asap.

**Comment by jayluxferro** [comment]
Let me try that and see. Thanks @basant-karki

**Comment by ghost** [comment]
@jayluxferro previous repo is deleted and version 0.4.9 is using old enginehash.csv from the old repo. So might be you will get an error.

**Comment by Impact-I** [comment]
Hello

Thanks for your interest in the project!
No point in using `0.4.9`
You must use `0.6.6`

When you say you were using an older version, do you mean that 0.4.9 worked successfully on same version of the application being processed?

The log of your device of the time interval would help me: starting from the launch of the application ending with its crash

**Comment by jayluxferro** [comment]
Alright @Impact-I , I will get you a sample log.

**Comment by ghost** [comment]
@Impact-I yes, reflutter version == 0.4.9 was working fine for me.

**Comment by ghost** [comment]
@Impact-I Log of my device. 
[iPhone Console.txt](https://github.com/Impact-I/reFlutter/files/8639055/iPhone.Console.txt)

**Comment by Impact-I** [comment]
@basant-karki What is your snapshot hash ? Today I will redo reFlutter logic and recompile engine for you
Maybe this will help

**Comment by ghost** [comment]
@Impact-I thank you for your help, can you please explain a bit more about what was the actual problem?

**Comment by ghost** [comment]
@Impact-I here is the snapshot hash : SnapshotHash: 9cf77f4405212c45daf608e1cd646852

**Comment by jayluxferro** [comment]
Hello @Impact-I , so when I hook into the runtime, this is what I get. The application just stops on launch. 

![Screen Shot 2022-05-06 at 10 06 11 AM](https://user-images.githubusercontent.com/8394019/167111638-e102ef03-8d3f-4a7f-8be1-bc3d8ce65967.png)

**Comment by jayluxferro** [comment]
Let me do some analysis on it using Frida and share. A hook into the application just terminates it.

<img width="560" alt="Screen Shot 2022-05-06 at 10 14 10 AM" src="https://user-images.githubusercontent.com/8394019/167112920-aab5187f-f529-4416-a467-7e110d24c08c.png">

**Comment by Impact-I** [comment]
> @Impact-I thank you for your help, can you please explain a bit more about what was the actual problem?

I didn't find the actual problem and it seems to me that the log is incomplete
I assume that the problem is in functionality of the new version - writing a file to the application folder leads to a crash

**Comment by ghost** [comment]
@Impact-I Thank you for the information. Now I'm waiting for the fix.

**Comment by Impact-I** [comment]
@jayluxferro What is your snapshot hash ?

**Comment by jayluxferro** [comment]
The libappHash is `d56742caf7b3b3f4bd2df93a9bbb5503`

**Comment by Impact-I** [comment]
@basant-karki , @jayluxferro , Hope it works for you

```
pip uninstall reflutter
pip install reflutter==0.6.8

reflutter example.ipa
```

`> I need to capture traffic only (Choose "No" if you also need a dump.dart) [Y/n]? Y`

```
sign and install ipa
```

**Comment by jayluxferro** [comment]
Hi @Impact-I , I tried version `0.6.8` and the app crashes. I took one ipa I refluttered and signed last week and tried doing same with the latest version and it still crashes.

I was able to load the one I refluttered and  signed last week on the phone but not with the current version.

A link to the IPA I used: https://www.icloud.com/iclouddrive/085U2IpGotj6P2tqouAKRfC9w#test_app

**Comment by Impact-I** [comment]
@jayluxferro The ipa you shared has a different snasphot hash `adf563436d12ba0d50ea5beb7f3be1bb`
Now, recompile the engine for this hash
I do not have an ios device nearby, I hope you can help me with the test

**Comment by jayluxferro** [comment]
Hi @Impact-I. About the IPA file I just realised I sent a version lower than what I initially used. For that I was able to reflutter it using the earlier version but not the current. I just thought if you try with that and it works then it should be fine. 

I'm recompiling the engine locally to see if it'll work. I just realised you've also initiated a build for that too.

**Comment by Impact-I** [comment]
@jayluxferro Build completed for https://www.icloud.com/iclouddrive/085U2IpGotj6P2tqouAKRfC9w#test_app 
(`adf563436d12ba0d50ea5beb7f3be1bb`)

Steps:

`pip install reflutter==0.6.8`
`reflutter test_app.ipa`

`> I need to capture traffic only (Choose "No" if you also need a dump.dart) [Y/n]? Y`

```
sign and install ipa
```

I hope this works

If that doesn't work, I'll erase all but the network patches and send the engine to build.
->
If it still doesn't work after that, then you're probably doing something wrong. At least I don't know what else can be done about it and where the problem is.

**Comment by Impact-I** [comment]
@jayluxferro Did you succeed?

**Comment by jayluxferro** [comment]
Hi @Impact-I , I tried it and it didn't work. I built the engine locally too and used that to reflutter it but it also didn't work. I thought it was a problem with my apple signing keys but I tested it with one I already refluttered some time back and my signing keys were okay. 

The reflutter process completes successfully; it just that the application still crashes on launch.

I wish you had an iPhone close by to test the `test_app.ipa`

**Comment by Impact-I** [comment]
@jayluxferro  If you have this in your logs
```
Bootstrapping failed for <FBApplicationProcess: 0x105f3a1f0; application<appexample>:-1> with error: <NSError: 0x282ee19b0; domain: RBSRequestErrorDomain; code: 5; reason: "The launchd job couldn't be started."> {
    underlyingError = <NSError: 0x282ee2070; domain: NSPOSIXErrorDomain; code: 3; reason: "No such process">
```
It's probably a problem with the signature.

Sorry for your time. Now I will make the last build leaving only network patches

**Comment by jayluxferro** [comment]
@Impact-I I checked but I didn't have any codesigning issues.   This is what I see what I run the app multiple times after it crashes.

![Screenshot 2022-05-07 at 2 20 16 PM](https://user-images.githubusercontent.com/8394019/167258555-c6afaf96-c2b1-4dd4-bf68-5fa76fc9cc9a.png)

**Comment by Impact-I** [comment]
@jayluxferro  Build completed for https://www.icloud.com/iclouddrive/085U2IpGotj6P2tqouAKRfC9w#test_app
(adf563436d12ba0d50ea5beb7f3be1bb)

Steps:
`remove release.RE.ipa`
`pip install reflutter==0.6.8`
`reflutter test_app.ipa`

`> I need to capture traffic only (Choose "No" if you also need a dump.dart) [Y/n]? Y`
```
sign and install ipa
```

This build should work with fewer patches than reFlutter from the old repository

**Comment by jayluxferro** [comment]
Hi @Impact-I , thanks that works. I will try building the engine locally for this hash `d56742caf7b3b3f4bd2df93a9bbb5503` and also try and see if it works. Will let you know if I find anything around this issue. Thanks a lot.

**Comment by Impact-I** [comment]
@jayluxferro Thanks for your feedback! Looks like I'll have to do two release branches v2 with dump patch and v3 with network only patch.

**Comment by jayluxferro** [comment]
Hi @Impact-I , I was able to build the engine for `d56742caf7b3b3f4bd2df93a9bbb5503`. It works fine now for traffic interception.  Hopefully we can get `dump.dart` working. Thanks a lot.

**Comment by ghost** [comment]
@Impact-I when you will release a new version for reflutter? reflutter==0.6.8 is not working for me. Thanks

**Comment by Impact-I** [comment]
@basant-karki A new version is expected within a week.

Build is expected for your engine `9cf77f4405212c45daf608e1cd646852` in 2 hours

**Comment by ghost** [comment]
Thank you for your great help :) @Impact-I

**Comment by Impact-I** [comment]
@basant-karki Build completed for `9cf77f4405212c45daf608e1cd646852`

Steps:
`remove release.RE.ipa (if exists in current folder)`
`pip install reflutter==0.6.8`
`reflutter app.ipa`

`> I need to capture traffic only (Choose "No" if you also need a dump.dart) [Y/n]? Y`
```
sign and install ipa
```

**Comment by ghost** [comment]
@Impact-I thanks you a lot, finally I'm able to intercept traffic on IOS.

**Comment by Impact-I** [comment]
@basant-karki Thanks for the test. I'm glad the new build works for you.

**Comment by Impact-I** [comment]
@jayluxferro , @basant-karki Please retest

`remove release.RE.ipa (if exists in current folder)`


`pip install reflutter==0.7.0`
`reflutter app.ipa`

`> Choose an option (Traffic monitoring and interception): 1`

```
sign and install ipa
```

**Comment by jayluxferro** [comment]
Hi @Impact-I , already tested it. It works fine. Have you deployed new engines for the dump dart?

**Comment by Impact-I** [comment]
@jayluxferro No, I just separated engines into a network patch and a dump.dart patch
I'm worried about whether the engine works correctly with the network and the new client version `0.7.0`

The build of v2 (network) was completed by end of [yesterday](https://github.com/Impact-I/reFlutter/actions/runs/2293520204).

**Comment by jayluxferro** [comment]
@Impact-I Oh okay. That's great. It works very well. Thanks

**Comment by Impact-I** [comment]
@jayluxferro , @basant-karki Fixed dump for IOS in `reflutter==0.7.1`

`Choose an option: 2. Display absolute code offset for functions`

**Comment by ghost** [comment]
Hello @Impact-I, the app is still crashing on reflutter==0.7.1, it's not opening now.

**Comment by ghost** [comment]
@Impact-I Here's the snapshot hash : 9cf77f4405212c45daf608e1cd646852 , previously it was working fine

![image](https://user-images.githubusercontent.com/60461905/168264013-05be0805-b509-47b5-8a35-c6da536b9eb7.png)

**Comment by Impact-I** [comment]
>previously it was working fine

@basant-karki By earlier do you mean test with version `0.6.8`, 5 days ago?

**Comment by Impact-I** [comment]
@basant-karki if choose [1/2]? 2

Steps Full:
`remove release.RE.ipa (if exists in current folder)`

`pip install reflutter==0.7.1`
`reflutter app.ipa`

`> Choose an option 2. Display absolute code offset for functions: 2`

```
sign and install ipa
```

**Comment by ghost** [comment]
> > previously it was working fine
> 
> @basant-karki By earlier do you mean test with version `0.6.8`, 5 days ago?

Yes @Impact-I but now it's crashing again while opening using the latest version 0.7.1

**Comment by jayluxferro** [comment]
> @jayluxferro , @basant-karki Fixed dump for IOS in `reflutter==0.7.1`
> 
> `Choose an option: 2. Display absolute code offset for functions`

Hi @Impact-I , dump works fine for me now. I have both network interception and dump. Thanks a lot.

![Screenshot 2022-05-14 at 4 32 09 AM](https://user-images.githubusercontent.com/8394019/168410735-653add16-5ac3-4f56-b94e-723cbf7e0403.png)

![Screenshot 2022-05-14 at 4 32 29 AM](https://user-images.githubusercontent.com/8394019/168410730-5a4bdb99-8dcf-4829-b474-16e289c4f008.png)

**Comment by jayluxferro** [comment]
> > > previously it was working fine
> > 
> > 
> > @basant-karki By earlier do you mean test with version `0.6.8`, 5 days ago?
> 
> Yes @Impact-I but now it's crashing again while opening using the latest version 0.7.1

@basant-karki , maybe try uninstalling all previous versions on your machine and reinstall the new one.

**Comment by Impact-I** [comment]
@basant-karki Can you share ipa file?

**Comment by ghost** [comment]
@Impact-I here is the ipa link : https://drive.google.com/file/d/18J0OoW5ad43BGaCrzLnwN7HeuXUnoOUa/view?usp=sharing

**Comment by Impact-I** [comment]
@basant-karki This has been successfully reproduced on ios 13.6
Traffic is successfully intercepted, the application works stably

`pip3 install reflutter==0.7.1`
`reflutter merchant_app.ipa`

Choose an option: **1**

What version of ios do you have? Check if everything is in order with the signature. I also recommend checking all logs since the application was launched.

**Comment by dgrivera** [comment]
Hello good sir, can anyone gave any instruction for the IOS refluttering? keep on encountering engine error.

**Comment by Impact-I** [comment]
@basant-karki , @dgrivera retest with reflutter 0.7.2 ?

**Comment by ghost** [comment]
@Impact-I @dgrivera reflutter version 0.7.2 works perfectly on IOS 14.7.1. the app works without any error and I'm successfully able to intercept traffic now. 

Thanks

**Comment by ghost** [comment]
@dgrivera please try again with version 0.7.2, may be this will work for you :)

**Comment by dgrivera** [comment]
@basant-karki using the latest version of reflutter but after the patch and I got re.release.ipa, I install the application when I open it the application crashes.

ios:14.3
Reflutter:0.7.2

Sorry for being a newbie🙏

**Comment by ghost** [comment]
Hello @dgrivera reflutter 0.7.2 works fine for me on both android and ios but if you don't mind, can you share your ipa?

**Comment by dgrivera** [comment]
@basant-karki sorry good sir but i cant as it was an enterprise app, but here is what i did:

1Install the new version app via testflight
2Then save the full ipa via crakerXI (JB)
3Patch the ipa via flutter 0.7.2 in powershell
4Got the patched ipa and install it to the device (ios 14.3) but when I open the app it crashes.

What can I do re install flutter? Or downgrade? What option can I do?

Thank you in advance.

**Comment by dgrivera** [comment]
@basant-karki  here is my snap-shot-hash: 1441d6b13b8623fa7fbf61433abebd31

**Comment by jayluxferro** [comment]
@Impact-I I also had the same issue today. Snapshot Hash: `1441d6b13b8623fa7fbf61433abebd31`
Built the engine locally and still had the same issue.

**Comment by dgrivera** [comment]
@Impact-I  maybe good sir you can help us?

**Comment by dgrivera** [comment]
@basant-karki  @Impact-I  any suggestion on our error in Snapshot Hash: 1441d6b13b8623fa7fbf61433abebd31

@jayluxferro may I ask how to locally built the engine? thank you in advance

**Comment by dgrivera** [comment]
@basant-karki @jayluxferro @Impact-I guys do we have a update?

**Comment by fxfyio** [comment]
> sign and install
What is this cli program?
