### ISSUE TITLE
Application crashes after patching (java.lang.UnsatisfiedLinkError: dlopen failed)

### ISSUE THREAD

**Issue by dtolstyi** [Impact-I/reFlutter#51]
After patching and trying to launch application on Android an error in logcat appears and app crashes:
```
05-06 12:06:11.841 25282 25282 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.app.RunApp: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~VTHe_C-zRg215VPslCtKfQ==/com.app-RnP-0YbA3rPoKly_jQM9LA==/base.apk!/lib/armeabi-v7a/libflutter.so" .dynamic section header was not found
05-06 12:06:11.841 25282 25282 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
...
```

**Comment by Impact-I** [comment]
Hello @dtolstyi 
Thanks for your interest in the project!
Can you share the apk file?

**Comment by dtolstyi** [comment]
Sure. https://www.transfernow.net/dl/20220506JfQm9DHj

**Comment by dtolstyi** [comment]
If I correctly understood, then the engine used in this apk is: `2.16.0-134.1.beta`.

**Comment by Impact-I** [comment]
@dtolstyi Thanks! 

Are you using an emulator?
I successfully reproduced this on OnePlus 6
No failure

>engine used in this apk is: `2.16.0-134.1.beta`

That's right your Snapshot Hash: `d56742caf7b3b3f4bd2df93a9bbb5503`

**Comment by dtolstyi** [comment]
Yes, emulator. It's not possible to use emulator with patched apk?

**Comment by Impact-I** [comment]
@dtolstyi 
Pay attention to supported architectures
arm64, arm32;

**Comment by dtolstyi** [comment]
Oh wow, I see. Thank you for information! I got `x86` emulator. I will try `arm64`. Thank you so much for your help @Impact-I !
