### ISSUE TITLE
HOOK "libapp.so" cannot get parameters

### ISSUE THREAD

**Issue by newNiu13** [Impact-I/reFlutter#63]
![U}LH`YGB~@N Z({HA9{(BPX](https://user-images.githubusercontent.com/95675214/167283148-fb9f2542-258b-41a0-bb8c-a720e620b23f.png)

function hookFunc() {

    var dumpOffset = 0x0000000000110D70	 + 0x0000000000115124 // _kDartIsolateSnapshotInstructions + code offset

    var argBufferSize = 150

    var address = Module.findBaseAddress('libapp.so') // libapp.so (Android) or App (IOS) 
    console.log('\n\nbaseAddress: ' + address.toString())

    var codeOffset = address.add(dumpOffset)
    console.log('codeOffset: ' + codeOffset.toString())
    console.log('')
    console.log('Wait..... ')

    Interceptor.attach(codeOffset, {
        onEnter: function(args) {

            console.log('')
            console.log('--------------------------------------------|')
            console.log('\n    Hook Function: ' + dumpOffset);
            console.log('')
            console.log('--------------------------------------------|')
            console.log('')

            for (var argStep = 0; argStep < 50; argStep++) {
                try {
                    dumpArgs(argStep, args[argStep], argBufferSize);
					console.log(args[argStep].toString() + "-------")
                } catch (e) {

                    break;
                }

            }

        },
        onLeave: function(retval) {
            console.log('RETURN : ' + retval)
            dumpArgs(0, retval, 150);
        }
    });

}

It's not about reflutter. I want to ask how to get parameters. My hook is my own application of "getmd5". I can't get the parameters I pass. Is it my wrong usage?

**Comment by newNiu13** [comment]
[release.RE-aligned-debugSigned.zip](https://github.com/Impact-I/reFlutter/files/8646491/release.RE-aligned-debugSigned.zip)

**Comment by HuRuWo** [comment]
确实不能通过hook code偏移来获得参数，因为这里获得的函数并不是真正的函数调用。
也就是说方法确实走了这里，但是参数不是这样显示的。
dartVm会重新编排这些参数，关于这些知识需要你去读取dartSDK了解。

**Comment by newNiu13** [comment]
> 确实不能通过hook code偏移来获得参数，因为这里获得的函数并不是真正的函数调用。 也就是说方法确实走了这里，但是参数不是这样显示的。 dartVm会重新编排这些参数，关于这些知识需要你去读取dartSDK了解。

英文的亏 看不懂 你有例子吗

**Comment by mashangxiu** [comment]
请问这个问题有解决的方法了吗

**Comment by Ha2ryZhang** [comment]
+1

**Comment by Nailik** [comment]
same issue for me :/
